using Content.Shared._Exodus.Mining.AutoMining;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Mining.AutoMining;

[GenerateTypedNameReferences]
public sealed partial class BulkAutoMiningLaserControl : PanelContainer
{
    public BulkAutoMiningLaserControl()
    {
        RobustXamlLoader.Load(this);
        WarmupBar.ToolTip = Loc.GetString("bulk-auto-mining-laser-warmup-hint");
    }

    public void UpdateState(BulkAutoMiningLaserState state, int index)
    {
        LaserName.Text = Loc.GetString("bulk-auto-mining-laser-name",
            ("name", state.ConsoleName ?? state.Name), ("index", index));
        LaserName.ToolTip = state.Name;
        HealthAmount.Text = Loc.GetString("bulk-auto-mining-laser-health",
            ("hp", (int)state.CurrentHp), ("max", (int)state.MaxHp));
        HealthBar.Value = state.MaxHp > 0 ? Math.Clamp(state.CurrentHp / state.MaxHp, 0, 1) : 0;
        WarmupBar.Value = Math.Clamp(state.Warmup, 0, 1);
        WarmupAmount.Text = Loc.GetString("bulk-auto-mining-laser-warmup",
            ("percent", (int)MathF.Round(state.Warmup * 100)), ("bonus", (int)MathF.Round(state.YieldBonus * 100)));
        BufferBar.Value = state.Capacity > 0 ? Math.Clamp((float)state.Stored / state.Capacity, 0, 1) : 0;
        BufferAmount.Text = Loc.GetString(state.Capacity > 0
                ? "bulk-auto-mining-laser-buffer" : "bulk-auto-mining-laser-buffer-unlimited",
            // Whole portions: floats reach Fluent as doubles and print every binary digit.
            ("stored", state.Stored / 100), ("capacity", state.Capacity / 100));

        var (status, hint, color) = state.Status switch
        {
            BulkAutoMiningLaserStatus.Ready => ("ready", (string?)null, Color.FromHex("#95BDB6")),
            BulkAutoMiningLaserStatus.Mining => ("mining", null, Color.FromHex("#F2B85F")),
            BulkAutoMiningLaserStatus.Searching => ("searching", "searching", Color.FromHex("#95BDB6")),
            BulkAutoMiningLaserStatus.Offline => ("offline", "power", Color.FromHex("#C1C6CB")),
            BulkAutoMiningLaserStatus.Busy => ("busy", "busy", Color.FromHex("#C1C6CB")),
            BulkAutoMiningLaserStatus.Full => ("full", "full", Color.FromHex("#F2B85F")),
            BulkAutoMiningLaserStatus.Linked => ("linked", "linked", BulkAutoMiningNavControl.ConsortiumGridColor),
            _ => ("blocked", "blocked", Color.FromHex("#F2B85F")),
        };
        LaserStatus.SetMessage(Loc.GetString($"bulk-auto-mining-laser-{status}",
            ("ship", state.LinkedShip ?? Loc.GetString("bulk-auto-mining-unknown-grid"))));
        LaserStatus.Modulate = color;
        StatusHint.Visible = hint != null;
        if (hint != null)
            StatusHint.SetMessage(Loc.GetString($"bulk-auto-mining-laser-hint-{hint}"));
    }
}
