using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Mining.AutoMining;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Mining.AutoMining;

[GenerateTypedNameReferences]
public sealed partial class BulkAutoMiningWindow : FancyWindow
{
    [Dependency] private IEntityManager _entities = default!;

    private readonly Dictionary<NetEntity, BulkAutoMiningLaserControl> _laserCards = new();
    private readonly Dictionary<NetEntity, (BoxContainer Row, Label Name, Button Remove)> _targetRows = new();
    private readonly HashSet<NetEntity> _stale = new();
    private BulkAutoMiningBoundUserInterfaceState? _state;
    private bool _linkMode;

    public event Action? OnStartPressed;
    public event Action? OnStopPressed;
    public event Action<NetEntity>? OnTargetRemoved;
    public event Action<NetEntity>? OnLinkRequested;
    public event Action<NetEntity>? OnLinkAccepted;
    public event Action<NetEntity>? OnLinkDeclined;
    public event Action<NetEntity>? OnLinkBroken;
    public BulkAutoMiningNavControl RadarControl => Radar;
    public BulkMiningLinkPanel LinkPanelControl => LinkPanel;
    public bool LinkMode => _linkMode;

    public BulkAutoMiningWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        // Reserve both sidebars before measuring the radar and its wrapping hint.
        foreach (var panel in Workspace.Children)
        {
            LayoutContainer.SetAnchorBottom(panel, 1);
            LayoutContainer.SetGrowHorizontal(panel, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(panel, LayoutContainer.GrowDirection.Constrain);
        }

        LayoutContainer.SetMarginRight(TargetsPanel, TargetsPanel.SetWidth);
        LayoutContainer.SetMarginRight(LinkPanel, LinkPanel.SetWidth);
        LayoutContainer.SetAnchorLeft(LasersPanel, 1);
        LayoutContainer.SetAnchorRight(LasersPanel, 1);
        LayoutContainer.SetMarginLeft(LasersPanel, -LasersPanel.SetWidth);
        LayoutContainer.SetAnchorRight(RadarPanel, 1);
        LayoutContainer.SetMarginLeft(RadarPanel, TargetsPanel.SetWidth + 12);
        LayoutContainer.SetMarginRight(RadarPanel, -LasersPanel.SetWidth - 12);

        var modes = new ButtonGroup();
        MiningModeButton.Group = modes;
        LinkModeButton.Group = modes;
        MiningModeButton.Pressed = true;
        MiningModeButton.OnPressed += _ => SetLinkMode(false);
        LinkModeButton.OnPressed += _ => SetLinkMode(true);

        StartButton.OnPressed += _ => OnStartPressed?.Invoke();
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        LinkPanel.OnRequest += grid => OnLinkRequested?.Invoke(grid);
        LinkPanel.OnAccept += grid => OnLinkAccepted?.Invoke(grid);
        LinkPanel.OnDecline += grid => OnLinkDeclined?.Invoke(grid);
        LinkPanel.OnBreak += grid => OnLinkBroken?.Invoke(grid);
        LinkPanel.OnSelect += SelectLinkTarget;
        Radar.OnLinkGridSelected += grid =>
        {
            Radar.SelectedLinkGrid = grid;
            RefreshLinkPanel();
        };
        SetLinkMode(false);
    }

    public void SetConsole(EntityUid consoleEntity)
    {
        Radar.SetConsole(consoleEntity);
    }

    protected override void Opened()
    {
        base.Opened();
        if (Parent == null)
            return;

        var available = Vector2.Max(MinSize, Parent.Size - new Vector2(20));
        SetSize = Vector2.Min(SetSize, available);
        Measure(available);
    }

    /// <summary>Switches between the mining and ship link tabs.</summary>
    public void SetLinkMode(bool linkMode)
    {
        _linkMode = linkMode;
        MiningModeButton.Pressed = !linkMode;
        LinkModeButton.Pressed = linkMode;
        TargetsPanel.Visible = !linkMode;
        LinkPanel.Visible = linkMode;
        Radar.LinkMode = linkMode;
        RadarTitle.Text = Loc.GetString(linkMode ? "bulk-auto-mining-link-radar-title" : "bulk-auto-mining-radar-title");
        ModeHint.Text = Loc.GetString(linkMode ? "bulk-auto-mining-mode-link-hint" : "bulk-auto-mining-mode-mining-hint");
        UpdateRadarHint();
        RefreshLinkPanel();
    }

    private void SelectLinkTarget(NetEntity grid)
    {
        Radar.SelectedLinkGrid = grid;
        if (!_linkMode)
            SetLinkMode(true);
        else
            RefreshLinkPanel();
    }

    private void RefreshLinkPanel()
    {
        if (_state == null)
            return;

        string? selectedName = null;
        if (Radar.SelectedLinkGrid is { } selected && _entities.TryGetEntity(selected, out var grid) &&
            _entities.TryGetComponent(grid, out MetaDataComponent? meta))
            selectedName = meta.EntityName;

        LinkPanel.UpdateState(_state.Link, Radar.SelectedLinkGrid, selectedName);
    }

    private void UpdateRadarHint()
    {
        var hint = _linkMode ? "bulk-auto-mining-link-radar-hint"
            : _state?.Active == true ? "bulk-auto-mining-select-while-active"
            : "bulk-auto-mining-radar-hint";
        RadarHint.SetMessage(Loc.GetString(hint));
    }

    public void UpdateState(BulkAutoMiningBoundUserInterfaceState state)
    {
        _state = state;
        Radar.UpdateMiningState(state);
        var mining = UpdateLasers(state.LinkedLasers);
        UpdateTargets(state);
        RefreshLinkPanel();

        var waiting = state.Active && mining == 0;
        MiningStatus.Text = Loc.GetString(state.Active
            ? waiting ? "bulk-auto-mining-status-waiting" : "bulk-auto-mining-status-active"
            : state.CanStart ? "bulk-auto-mining-status-ready" : "bulk-auto-mining-status-idle");
        MiningStatus.FontColorOverride = state.Active ? Color.FromHex("#F2B85F") : Color.FromHex("#C3D9D7");
        LaserSummary.Text = Loc.GetString("bulk-auto-mining-laser-summary",
            ("mining", mining), ("total", state.LinkedLasers.Count));

        var ships = state.Link.Members.Count;
        ConsortiumBadge.Visible = ships > 1;
        ConsortiumBadgeLabel.Text = Loc.GetString("bulk-auto-mining-consortium-badge",
            ("count", ships), ("percent", Math.Round(state.Link.Bonus * 100, 1)));
        ConsortiumBadge.ToolTip = Loc.GetString("bulk-auto-mining-consortium-badge-tooltip");

        var hint = state.Active
            ? waiting ? "bulk-auto-mining-hint-waiting" : "bulk-auto-mining-hint-active"
            : state.LinkedLasers.Count == 0 ? "bulk-auto-mining-no-lasers"
            : !state.CanStart ? "bulk-auto-mining-start-no-ready-emitter"
            : state.SelectedTargets.Count == 0 ? "bulk-auto-mining-select-hint"
            : "bulk-auto-mining-hint-ready";
        OperationHint.SetMessage(Loc.GetString(hint));
        UpdateRadarHint();
        SelectedTargetsSummary.Text = Loc.GetString("bulk-auto-mining-selected-targets-summary",
            ("count", state.SelectedTargets.Count), ("max", state.MaxSelectableTargets));

        StartButton.Disabled = state.Active || !state.CanStart || state.SelectedTargets.Count == 0;
        StartButton.ToolTip = StartButton.Disabled ? Loc.GetString(hint) : null;
        StopButton.Disabled = !state.Active;
        MiningProgress.Value = state.TotalTiles > 0
            ? Math.Clamp((float)state.ProcessedTiles / state.TotalTiles, 0, 1) : 0;
        ProgressLabel.Text = state.TotalTiles > 0
            ? Loc.GetString("bulk-auto-mining-progress", ("processed", state.ProcessedTiles), ("total", state.TotalTiles))
            : Loc.GetString("bulk-auto-mining-progress-empty");
    }

    private void UpdateTargets(BulkAutoMiningBoundUserInterfaceState state)
    {
        _stale.Clear();
        _stale.UnionWith(_targetRows.Keys);
        foreach (var target in state.SelectedTargets)
        {
            _stale.Remove(target.Grid);
            if (!_targetRows.TryGetValue(target.Grid, out var row))
            {
                row = (new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 },
                    new Label { HorizontalExpand = true, ClipText = true },
                    new Button { Text = Loc.GetString("bulk-auto-mining-remove-target"), MinHeight = 30 });
                var grid = target.Grid;
                row.Remove.OnPressed += _ => OnTargetRemoved?.Invoke(grid);
                row.Row.AddChild(row.Name);
                row.Row.AddChild(row.Remove);
                TargetsBox.AddChild(row.Row);
                _targetRows.Add(grid, row);
            }

            row.Name.Text = target.Name ?? Loc.GetString("bulk-auto-mining-unknown-grid");
            row.Name.ToolTip = row.Name.Text;
            row.Remove.Disabled = state.Active;
            row.Remove.ToolTip = state.Active ? Loc.GetString("bulk-auto-mining-select-while-active") : null;
        }

        foreach (var grid in _stale)
        {
            if (_targetRows.Remove(grid, out var row))
                TargetsBox.RemoveChild(row.Row);
        }

        NoTargetsLabel.Visible = state.SelectedTargets.Count == 0;
    }

    private int UpdateLasers(List<BulkAutoMiningLaserState> lasers)
    {
        _stale.Clear();
        _stale.UnionWith(_laserCards.Keys);
        var mining = 0;
        for (var i = 0; i < lasers.Count; i++)
        {
            var laser = lasers[i];
            _stale.Remove(laser.Emitter);
            if (!_laserCards.TryGetValue(laser.Emitter, out var card))
            {
                card = new BulkAutoMiningLaserControl();
                LasersBox.AddChild(card);
                _laserCards.Add(laser.Emitter, card);
            }

            card.UpdateState(laser, i + 1);
            if (laser.Status == BulkAutoMiningLaserStatus.Mining)
                mining++;
        }

        foreach (var emitter in _stale)
        {
            if (_laserCards.Remove(emitter, out var card))
                LasersBox.RemoveChild(card);
        }

        NoLasersLabel.Visible = lasers.Count == 0;
        return mining;
    }
}
