using Content.Client.Message;
using Content.Shared._Exodus.CCVar;
using Content.Shared._Exodus.Mining.AutoMining;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._Exodus.Mining.AutoMining;

/// <summary>Consortium tab of the bulk mining console: bonuses, requests, active links and nearby ships.</summary>
[GenerateTypedNameReferences]
public sealed partial class BulkMiningLinkPanel : BoxContainer
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public static readonly Color AvailableColor = Color.FromHex("#6FE3C0");
    public static readonly Color WarningColor = Color.FromHex("#F2B85F");
    public static readonly Color MutedColor = Color.FromHex("#9AA5AD");

    private readonly Dictionary<NetEntity, BulkMiningLinkShipRow> _shipRows = new();
    private readonly Dictionary<NetEntity, BulkMiningLinkCard> _linkCards = new();
    private readonly HashSet<NetEntity> _stale = new();

    /// <summary>Ships currently asking this one to link.</summary>
    public int IncomingRequests { get; private set; }

    /// <summary>Active links shown as cards.</summary>
    public int ActiveLinks => _linkCards.Count;

    public event Action<NetEntity>? OnRequest;
    public event Action<NetEntity>? OnAccept;
    public event Action<NetEntity>? OnDecline;
    public event Action<NetEntity>? OnBreak;
    public event Action<NetEntity>? OnSelect;

    public BulkMiningLinkPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <param name="selectedName">Name of the ship picked on the radar, for ships that cannot answer.</param>
    public void UpdateState(BulkMiningLinkUiState state, NetEntity? selected, string? selectedName)
    {
        UpdateConsortium(state);
        UpdateShips(state, selected);
        UpdateLinks(state);

        FreeLasers.Text = Loc.GetString("bulk-auto-mining-link-free-lasers", ("count", state.FreeLasers));
        FreeLasers.FontColorOverride = state.FreeLasers > 0 ? AvailableColor : WarningColor;

        var name = FormattedMessage.EscapeText(selectedName ?? Loc.GetString("bulk-auto-mining-unknown-grid"));
        string hint;
        if (selected is not { } grid)
            hint = Loc.GetString("bulk-auto-mining-link-radar-hint");
        else if (_shipRows.ContainsKey(grid) || _linkCards.ContainsKey(grid))
            hint = Loc.GetString("bulk-auto-mining-link-selected", ("name", name));
        else
            hint = Loc.GetString("bulk-auto-mining-link-selected-unavailable", ("name", name));

        if (state.FreeLasers == 0)
            hint += "\n" + Loc.GetString("bulk-auto-mining-link-no-free-own-hint");

        SelectionHint.SetMarkup(hint);
    }

    private void UpdateConsortium(BulkMiningLinkUiState state)
    {
        var count = Math.Max(1, state.Members.Count);
        ConsortiumSize.Text = Loc.GetString("bulk-auto-mining-link-consortium-size", ("count", count));
        var percent = Math.Round(state.Bonus * 100, 1);
        SpeedBonus.Text = Loc.GetString("bulk-auto-mining-link-bonus-value", ("percent", percent));
        YieldBonus.Text = Loc.GetString("bulk-auto-mining-link-bonus-value", ("percent", percent));
        var max = _cfg.GetCVar(EXCVars.BulkMiningLinkMaxBonus);
        BonusBar.Value = max > 0 ? Math.Clamp(state.Bonus / max, 0, 1) : 0;
        var next = state.NextBonus - state.Bonus;
        NextBonus.SetMarkup(next > 0.0005f
            ? Loc.GetString("bulk-auto-mining-link-next-bonus", ("percent", Math.Round(next * 100, 1)))
            : Loc.GetString("bulk-auto-mining-link-bonus-max"));

        MembersBox.RemoveAllChildren();
        for (var i = 0; i < state.Members.Count; i++)
        {
            var member = state.Members[i];
            MembersBox.AddChild(new Label
            {
                Text = Loc.GetString(i == 0 ? "bulk-auto-mining-link-member-self" : "bulk-auto-mining-link-member",
                    ("name", member.Name)),
                FontColorOverride = i == 0 ? Color.FromHex("#C8FBFF") : BulkAutoMiningNavControl.ConsortiumGridColor,
                ClipText = true,
            });
        }
    }

    private void UpdateShips(BulkMiningLinkUiState state, NetEntity? selected)
    {
        _stale.Clear();
        _stale.UnionWith(_shipRows.Keys);
        var incoming = 0;
        var listed = 0;
        foreach (var ship in state.Ships)
        {
            // Linked ships are listed with their link card instead.
            if (ship.Status == BulkMiningLinkShipStatus.Linked)
                continue;

            _stale.Remove(ship.Grid);
            if (!_shipRows.TryGetValue(ship.Grid, out var row))
            {
                row = new BulkMiningLinkShipRow(ship.Grid);
                row.OnRequest += grid => OnRequest?.Invoke(grid);
                row.OnAccept += grid => OnAccept?.Invoke(grid);
                row.OnDecline += grid => OnDecline?.Invoke(grid);
                row.OnSelect += grid => OnSelect?.Invoke(grid);
                _shipRows.Add(ship.Grid, row);
            }

            var target = ship.Status == BulkMiningLinkShipStatus.IncomingRequest ? IncomingBox : ShipsBox;
            if (row.Parent != target)
            {
                row.Orphan();
                target.AddChild(row);
            }

            row.UpdateState(ship, selected == ship.Grid, state.FreeLasers > 0);
            if (target == IncomingBox)
                incoming++;
            else
                listed++;
        }

        foreach (var grid in _stale)
        {
            if (_shipRows.Remove(grid, out var row))
                row.Orphan();
        }

        IncomingRequests = incoming;
        IncomingSection.Visible = incoming > 0;
        NoShipsLabel.Visible = listed == 0;
    }

    private void UpdateLinks(BulkMiningLinkUiState state)
    {
        _stale.Clear();
        _stale.UnionWith(_linkCards.Keys);
        foreach (var link in state.Links)
        {
            _stale.Remove(link.Grid);
            if (!_linkCards.TryGetValue(link.Grid, out var card))
            {
                card = new BulkMiningLinkCard(link.Grid);
                card.OnBreak += grid => OnBreak?.Invoke(grid);
                card.OnSelect += grid => OnSelect?.Invoke(grid);
                LinksBox.AddChild(card);
                _linkCards.Add(link.Grid, card);
            }

            card.UpdateState(link);
        }

        foreach (var grid in _stale)
        {
            if (_linkCards.Remove(grid, out var card))
                card.Orphan();
        }

        LinksSection.Visible = state.Links.Count > 0;
    }
}

/// <summary>A nearby ship: distance, whether it can link right now, and the matching request buttons.</summary>
public sealed class BulkMiningLinkShipRow : PanelContainer
{
    private readonly NetEntity _grid;
    private readonly StyleBoxFlat _background = new() { BackgroundColor = Color.FromHex("#202A33") };
    private readonly Button _name;
    private readonly Label _distance;
    private readonly Label _status;
    private readonly Button _primary;
    private readonly Button _secondary;
    private BulkMiningLinkShipStatus _shownStatus;

    public event Action<NetEntity>? OnRequest;
    public event Action<NetEntity>? OnAccept;
    public event Action<NetEntity>? OnDecline;
    public event Action<NetEntity>? OnSelect;

    public BulkMiningLinkShipRow(NetEntity grid)
    {
        _grid = grid;
        PanelOverride = _background;
        _name = new Button { HorizontalExpand = true, ClipText = true, StyleClasses = { "OpenRight" } };
        _distance = new Label { StyleClasses = { "LabelSubText" }, VerticalAlignment = VAlignment.Center, Margin = new Thickness(6, 0, 0, 0) };
        _status = new Label { HorizontalExpand = true, ClipText = true, VerticalAlignment = VAlignment.Center };
        _primary = new Button { MinWidth = 96, MinHeight = 28 };
        _secondary = new Button { MinWidth = 80, MinHeight = 28, StyleClasses = { "Caution" }, Visible = false };

        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        header.AddChild(_name);
        header.AddChild(_distance);
        var actions = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
        actions.AddChild(_status);
        actions.AddChild(_primary);
        actions.AddChild(_secondary);
        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(8, 6),
        };
        body.AddChild(header);
        body.AddChild(actions);
        AddChild(body);

        _name.OnPressed += _ => OnSelect?.Invoke(_grid);
        _primary.OnPressed += _ =>
        {
            switch (_shownStatus)
            {
                case BulkMiningLinkShipStatus.IncomingRequest:
                    OnAccept?.Invoke(_grid);
                    break;
                case BulkMiningLinkShipStatus.OutgoingRequest:
                    OnDecline?.Invoke(_grid);
                    break;
                default:
                    OnRequest?.Invoke(_grid);
                    break;
            }
        };
        _secondary.OnPressed += _ => OnDecline?.Invoke(_grid);
    }

    public void UpdateState(BulkMiningLinkShipState state, bool selected, bool ownFree)
    {
        _shownStatus = state.Status;
        _background.BackgroundColor = Color.FromHex(selected ? "#25404A" : "#202A33");
        _background.BorderColor = BulkAutoMiningNavControl.LinkTargetColor;
        _background.BorderThickness = selected ? new Thickness(2, 0, 0, 0) : new Thickness(0);
        _name.Text = state.Name;
        _name.ToolTip = state.Name;
        _distance.Text = Loc.GetString("bulk-auto-mining-link-distance", ("distance", (int)MathF.Round(state.Distance)));

        var seconds = (int)MathF.Ceiling(state.RequestTimeLeft);
        var (status, color) = state.Status switch
        {
            BulkMiningLinkShipStatus.Available => (Loc.GetString("bulk-auto-mining-link-status-available"), BulkMiningLinkPanel.AvailableColor),
            BulkMiningLinkShipStatus.NoFreeLaser => (Loc.GetString("bulk-auto-mining-link-status-no-free-laser"), BulkMiningLinkPanel.MutedColor),
            BulkMiningLinkShipStatus.Obstructed => (Loc.GetString("bulk-auto-mining-link-status-obstructed"), BulkMiningLinkPanel.WarningColor),
            BulkMiningLinkShipStatus.OutgoingRequest => (Loc.GetString("bulk-auto-mining-link-status-outgoing", ("seconds", seconds)), BulkAutoMiningNavControl.RequestGridColor),
            BulkMiningLinkShipStatus.IncomingRequest => (Loc.GetString("bulk-auto-mining-link-status-incoming", ("seconds", seconds)), BulkAutoMiningNavControl.LinkTargetColor),
            _ => (Loc.GetString("bulk-auto-mining-link-status-linked"), BulkAutoMiningNavControl.ConsortiumGridColor),
        };
        _status.Text = status;
        _status.FontColorOverride = color;
        _status.ToolTip = status;

        _secondary.Visible = state.Status == BulkMiningLinkShipStatus.IncomingRequest;
        _secondary.Text = Loc.GetString("bulk-auto-mining-link-decline");
        _primary.Text = Loc.GetString(state.Status switch
        {
            BulkMiningLinkShipStatus.IncomingRequest => "bulk-auto-mining-link-accept",
            BulkMiningLinkShipStatus.OutgoingRequest => "bulk-auto-mining-link-cancel",
            _ => "bulk-auto-mining-link-request",
        });

        // Accepting or requesting needs a free laser here; withdrawing a request never does.
        var needsLaser = state.Status != BulkMiningLinkShipStatus.OutgoingRequest;
        _primary.Disabled = needsLaser && !ownFree;
        _primary.ToolTip = _primary.Disabled ? Loc.GetString("bulk-auto-mining-link-no-free-own") : null;
    }
}

/// <summary>An active consortium link: the laser pair, beam length against its range and line stability.</summary>
public sealed class BulkMiningLinkCard : PanelContainer
{
    private readonly NetEntity _grid;
    private readonly StyleBoxFlat _background = new()
    {
        BackgroundColor = Color.FromHex("#172528"),
        BorderColor = BulkAutoMiningNavControl.ConsortiumGridColor,
        BorderThickness = new Thickness(3, 0, 0, 0),
    };

    private readonly StyleBoxFlat _rangeFill = new() { BackgroundColor = BulkAutoMiningNavControl.ConsortiumGridColor };
    private readonly Button _name;
    private readonly Label _lasers;
    private readonly ProgressBar _range;
    private readonly Label _distance;
    private readonly Label _status;

    public event Action<NetEntity>? OnBreak;
    public event Action<NetEntity>? OnSelect;

    public BulkMiningLinkCard(NetEntity grid)
    {
        _grid = grid;
        PanelOverride = _background;
        _name = new Button { HorizontalExpand = true, ClipText = true, StyleClasses = { "OpenRight" } };
        var breakButton = new Button
        {
            Text = Loc.GetString("bulk-auto-mining-link-break"),
            StyleClasses = { "Caution" },
            MinHeight = 28,
        };
        _lasers = new Label { ClipText = true, FontColorOverride = Color.FromHex("#C8FBFF") };
        _range = new ProgressBar { MinValue = 0, MaxValue = 1, SetHeight = 6, ForegroundStyleBoxOverride = _rangeFill };
        _distance = new Label { StyleClasses = { "LabelSubText" } };
        _status = new Label { ClipText = true };

        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
        header.AddChild(_name);
        header.AddChild(breakButton);
        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(10, 6),
        };
        body.AddChild(header);
        body.AddChild(_lasers);
        body.AddChild(_range);
        body.AddChild(_distance);
        body.AddChild(_status);
        AddChild(body);

        _name.OnPressed += _ => OnSelect?.Invoke(_grid);
        breakButton.OnPressed += _ => OnBreak?.Invoke(_grid);
    }

    public void UpdateState(BulkMiningLinkState state)
    {
        _name.Text = state.Name;
        _name.ToolTip = state.Name;
        _lasers.Text = Loc.GetString("bulk-auto-mining-link-lasers", ("own", state.LaserName), ("partner", state.PartnerLaserName));
        var fraction = state.Range > 0 ? Math.Clamp(state.Distance / state.Range, 0, 1) : 0;
        _range.Value = fraction;
        var strained = state.Obstructed || fraction > 0.85f;
        _rangeFill.BackgroundColor = strained ? BulkMiningLinkPanel.WarningColor : BulkAutoMiningNavControl.ConsortiumGridColor;
        _background.BorderColor = _rangeFill.BackgroundColor;
        _distance.Text = Loc.GetString("bulk-auto-mining-link-range",
            ("distance", (int)MathF.Round(state.Distance)), ("range", (int)MathF.Round(state.Range)));
        _status.Text = Loc.GetString(state.Obstructed ? "bulk-auto-mining-link-unstable" : "bulk-auto-mining-link-stable");
        _status.FontColorOverride = state.Obstructed ? BulkMiningLinkPanel.WarningColor : BulkMiningLinkPanel.AvailableColor;
    }
}
