using System.Numerics;
using Content.Client.Materials;
using Content.Client.Message;
using Content.Shared._Exodus.Mining.Pipes;
using Content.Shared.Atmos;
using Content.Shared.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Exodus.Mining.Pipes.UI;

[GenerateTypedNameReferences]
public sealed partial class MiningRefineryStorageControl : BoxContainer
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    private readonly StyleBoxFlat _gasFill = new(Color.FromHex("#687747"));
    private (MiningRefineryStorageState, Gas, ProtoId<MaterialPrototype>, float, float)? _lastReadings;

    public MiningRefineryStorageControl(EntityUid owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        GasBar.ForegroundStyleBoxOverride = _gasFill;
        SlurryBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#946037"));
        if (_entities.TryGetComponent(owner, out MiningRefineryComponent? refinery))
            UpdateReadings(refinery);
    }

    /// <summary>
    /// A scroll container reports no size of its own, so keep the column as wide as the widest reading
    /// instead of letting the lathe squeeze it and clip the text.
    /// </summary>
    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        var size = base.MeasureOverride(availableSize);
        var scrollBar = 0f;
        foreach (var child in Scroll.Children)
        {
            if (child is VScrollBar bar)
                scrollBar = bar.DesiredSize.X;
        }

        return size with { X = MathF.Max(size.X, Readings.DesiredSize.X + scrollBar) };
    }

    public void UpdateReadings(MiningRefineryComponent refinery)
    {
        var state = refinery.StorageState;
        var readings = (state, refinery.ExhaustGas, refinery.SlurryMaterial, refinery.CorrosionThreshold, refinery.ExplosionThreshold);
        if (_lastReadings == readings)
            return;

        _lastReadings = readings;
        var material = _prototypes.Index(refinery.SlurryMaterial);
        var unitVolume = Math.Max(1, _entities.System<MaterialStorageSystem>().GetSheetVolume(material));
        var stored = Math.Round(state.SlurryStored / (double)unitVolume, 1);
        SlurryBar.Visible = state.SlurryCapacity != null;
        UnlimitedSlurry.Visible = !SlurryBar.Visible;
        if (state.SlurryCapacity is { } capacity)
        {
            SlurryBar.Value = capacity > 0 ? Math.Clamp(state.SlurryStored / (float)capacity, 0, 1) : 0;
            SlurryAmount.Text = Loc.GetString("bulk-mining-refinery-ui-slurry-amount",
                ("stored", stored), ("capacity", Math.Round(capacity / (double)unitVolume, 1)));
        }
        else
        {
            UnlimitedSlurry.Text = Loc.GetString("bulk-mining-refinery-ui-slurry-unlimited", ("stored", stored));
        }

        GasName.Text = Loc.GetString("bulk-mining-refinery-ui-gas", ("gas", Atmospherics.GasNames[refinery.ExhaustGas]));
        var limit = refinery.ExplosionThreshold > 0 ? refinery.ExplosionThreshold : refinery.CorrosionThreshold;
        GasBar.Value = limit > 0 ? Math.Clamp(state.GasMoles / limit, 0, 1) : 0;
        GasAmount.Text = Loc.GetString(limit > 0 ? "bulk-mining-refinery-ui-gas-amount" : "bulk-mining-refinery-ui-gas-unlimited",
            ("stored", Math.Round(state.GasMoles, 1)), ("capacity", limit));
        GasPressure.Text = Loc.GetString("bulk-mining-refinery-ui-pressure", ("pressure", Math.Round(state.GasPressure, 1)));
        var warning = state.GasMoles > refinery.CorrosionThreshold;
        var critical = refinery.ExplosionThreshold > 0 && state.GasMoles >= refinery.ExplosionThreshold * 0.9f;
        _gasFill.BackgroundColor = Color.FromHex(critical ? "#A53C38" : warning ? "#A46B27" : "#687747");
        GasWarning.Visible = warning || critical;
        GasWarning.SetMarkup(Loc.GetString(critical ? "bulk-mining-refinery-ui-critical" : "bulk-mining-refinery-ui-corrosion",
            ("limit", refinery.ExplosionThreshold)));
        ConsortiumInfo.SetMarkup(Loc.GetString(state.LinkedShips > 1
                ? "bulk-mining-refinery-ui-consortium-linked"
                : "bulk-mining-refinery-ui-consortium-alone",
            ("count", state.LinkedShips), ("percent", Math.Round(state.LinkBonus * 100, 1))));
    }
}
