// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared._Exodus.Virology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Virology;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorWindow : DefaultWindow
{
    public VaccinatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(VaccinatorBoundUserInterfaceState state)
    {
        ScanProgress.SetOperation(state.Status, state.OperationEnd, state.OperationDuration);

        StationLabel.Text = state.StationName is { } station
            ? Loc.GetString("virology-console-station", ("name", station))
            : Loc.GetString("virology-console-station-unknown");

        StatusLabel.Text = state.Status switch
        {
            VirologyMachineStatus.NoSample => Loc.GetString("vaccinator-no-sample"),
            VirologyMachineStatus.Scanning => Loc.GetString("vaccinator-scanning"),
            VirologyMachineStatus.Printing => Loc.GetString("vaccinator-printing"),
            VirologyMachineStatus.Result => Loc.GetString("vaccinator-result"),
            _ => Loc.GetString("vaccinator-ready"),
        };

        ResultsContainer.DisposeAllChildren();
        if (state.Status == VirologyMachineStatus.Result && state.Viruses.Count == 0)
            ResultsContainer.AddChild(new Label { Text = Loc.GetString("virology-no-pathogens") });
        foreach (var virus in state.Viruses)
            ResultsContainer.AddChild(BuildVirusBlock(virus));

        BufferLabel.Text = Loc.GetString("vaccinator-buffer", ("amount", state.BufferTricordrazine));

        var idleWithSample = state.Status is VirologyMachineStatus.Ready or VirologyMachineStatus.Result;
        var hasResult = state.Status == VirologyMachineStatus.Result;
        ScanButton.Disabled = !idleWithSample;
        TransferButton.Disabled = !idleWithSample;
        CreateVaccineButton.Disabled = !hasResult;
        PrintButton.Disabled = !hasResult;
        EjectButton.Disabled = state.Status == VirologyMachineStatus.NoSample;
    }

    private static VirusResultBlock BuildVirusBlock(VaccinatorVirusResult virus)
    {
        var block = new VirusResultBlock();

        block.SetHeader(virus.Name != null
            ? Loc.GetString("vaccinator-virus-name", ("name", virus.Name))
            : Loc.GetString("vaccinator-virus-unknown"));

        if (virus.Suppressed)
            block.SetSuppressed(Loc.GetString("vaccinator-suppressed"));

        block.SetSymptoms(virus.Symptoms);

        if (virus.UnreadableCount > 0)
            block.SetUnreadable(Loc.GetString("vaccinator-unreadable", ("count", virus.UnreadableCount)));

        if (virus.CureReagents.Count > 0 || virus.CureHidden)
            block.SetCure(virus.CureReagents.Count > 0
                ? Loc.GetString("vaccinator-cure", ("reagents", string.Join(", ", virus.CureReagents)))
                : Loc.GetString("vaccinator-cure-hidden"));

        return block;
    }
}
