// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared._Exodus.Virology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Virology;

[GenerateTypedNameReferences]
public sealed partial class VirusDiagnoserWindow : DefaultWindow
{
    public VirusDiagnoserWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(VirusDiagnoserBoundUserInterfaceState state)
    {
        ScanProgress.SetOperation(state.Status, state.OperationEnd, state.OperationDuration);

        StationLabel.Text = state.StationName is { } station
            ? Loc.GetString("virology-console-station", ("name", station))
            : Loc.GetString("virology-console-station-unknown");

        StatusLabel.Text = state.Status switch
        {
            VirologyMachineStatus.NoSample => Loc.GetString("disease-diagnoser-no-sample"),
            VirologyMachineStatus.Scanning => Loc.GetString("disease-diagnoser-scanning"),
            VirologyMachineStatus.Printing => Loc.GetString("disease-diagnoser-printing"),
            VirologyMachineStatus.Result => Loc.GetString("disease-diagnoser-result"),
            _ => Loc.GetString("disease-diagnoser-ready"),
        };

        ResultsContainer.DisposeAllChildren();
        if (state.Status == VirologyMachineStatus.Result && state.Viruses.Count == 0)
            ResultsContainer.AddChild(new Label { Text = Loc.GetString("virology-no-pathogens") });
        foreach (var virus in state.Viruses)
            ResultsContainer.AddChild(BuildVirusBlock(virus));

        BufferLabel.Text = Loc.GetString("disease-diagnoser-buffer", ("amount", state.BufferMutagen));

        var idleWithSample = state.Status is VirologyMachineStatus.Ready or VirologyMachineStatus.Result;
        var hasResult = state.Status == VirologyMachineStatus.Result;
        ScanButton.Disabled = !idleWithSample;
        TransferButton.Disabled = !idleWithSample;
        CopyButton.Disabled = !idleWithSample;
        PrintButton.Disabled = !hasResult;
        EjectButton.Disabled = state.Status == VirologyMachineStatus.NoSample;
    }

    private static VirusResultBlock BuildVirusBlock(VirusDiagnoserResult virus)
    {
        var block = new VirusResultBlock();

        block.SetHeader(virus.Name != null
            ? Loc.GetString("disease-diagnoser-virus-name", ("name", virus.Name))
            : Loc.GetString("disease-diagnoser-virus-unknown"));

        block.SetSymptoms(virus.Symptoms);

        if (virus.Transmission != VirusTransmissionVector.None)
        {
            var vectors = new List<string>();
            if ((virus.Transmission & VirusTransmissionVector.Contact) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-contact"));
            if ((virus.Transmission & VirusTransmissionVector.Proximity) != 0)
                vectors.Add(Loc.GetString("disease-diagnoser-vector-proximity"));

            block.SetTransmission(Loc.GetString("disease-diagnoser-transmission", ("vectors", string.Join(", ", vectors))));
        }

        if (virus.UnreadableCount > 0)
            block.SetUnreadable(Loc.GetString("disease-diagnoser-unreadable", ("count", virus.UnreadableCount)));

        return block;
    }
}
