// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Virology;

[GenerateTypedNameReferences]
public sealed partial class VirusResultBlock : BoxContainer
{
    public VirusResultBlock()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetHeader(string text)
    {
        NameLabel.Text = text;
    }

    public void SetSuppressed(string? text)
    {
        SuppressedLabel.Text = text;
        SuppressedLabel.Visible = text != null;
    }

    public void SetSymptoms(IEnumerable<string> symptoms)
    {
        SymptomsContainer.DisposeAllChildren();
        foreach (var symptom in symptoms)
            SymptomsContainer.AddChild(new Label { Text = $" · {symptom}", Margin = new Thickness(4, 0, 0, 0) });
    }

    public void SetTransmission(string? text)
    {
        TransmissionLabel.Text = text;
        TransmissionLabel.Visible = text != null;
    }

    public void SetUnreadable(string? text)
    {
        UnreadableLabel.Text = text;
        UnreadableLabel.Visible = text != null;
    }

    public void SetCure(string? text)
    {
        CureLabel.Text = text;
        CureLabel.Visible = text != null;
    }
}
