using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.TerritoryIncome;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.TerritoryIncome;

[GenerateTypedNameReferences]
public sealed partial class TerritoryIncomeWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public event Action<int>? Withdraw;

    private TerritoryIncomeUiState? _state;
    private TimeSpan _nextTimerUpdate;

    public TerritoryIncomeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        AmountInput.IsValid = amount => amount > 0 && amount <= (_state?.MaxWithdrawal ?? 1000);
        AmountInput.InitDefaultButtons();
        AmountInput.Value = 1;
        AmountInput.ValueChanged += _ => UpdateControls();
        WithdrawButton.OnPressed += _ =>
        {
            if (_state is { Active: true } && AmountInput.Value <= _state.Balance)
                Withdraw?.Invoke(AmountInput.Value);
        };
        UpdateControls();
    }

    public void UpdateState(TerritoryIncomeUiState state)
    {
        _state = state;
        Title = Loc.GetString(state.AccountName);
        var currency = Loc.GetString(state.CurrencyName);
        BalanceLabel.Text = Loc.GetString("territory-income-balance", ("amount", state.Balance), ("currency", currency));
        RateLabel.Text = Loc.GetString("territory-income-rate",
            ("amount", (long) state.Points * state.CurrencyPerPoint), ("currency", currency),
            ("minutes", state.Interval.TotalMinutes));
        TerritoriesLabel.Text = Loc.GetString("territory-income-territories",
            ("count", state.Territories.Count), ("points", state.Points));

        TerritoryList.DisposeAllChildren();
        if (state.Territories.Count == 0)
            TerritoryList.AddChild(new Label { Text = Loc.GetString("territory-income-no-territories") });

        foreach (var territory in state.Territories)
        {
            var label = new RichTextLabel();
            // Grid names are plain text, not player-provided markup.
            label.SetMessage(Loc.GetString("territory-income-territory", ("name", territory.Name), ("points", territory.Points)));
            TerritoryList.AddChild(label);
        }

        if (AmountInput.Value > state.MaxWithdrawal)
            AmountInput.Value = Math.Max(1, state.MaxWithdrawal);

        UpdateTimer();
        UpdateControls();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_state == null || _timing.CurTime < _nextTimerUpdate)
            return;

        UpdateTimer();
    }

    private void UpdateTimer()
    {
        _nextTimerUpdate = _timing.CurTime + TimeSpan.FromSeconds(1);
        if (_state == null)
            return;

        if (!_state.Active)
        {
            TimerLabel.Text = Loc.GetString("territory-income-offline");
            return;
        }

        var seconds = Math.Max(0, (int) Math.Ceiling((_state.NextPayout - _timing.CurTime).TotalSeconds));
        TimerLabel.Text = Loc.GetString("territory-income-next-payment",
            ("minutes", seconds / 60), ("seconds", (seconds % 60).ToString("D2")));
    }

    private void UpdateControls()
    {
        var active = _state is { Active: true };
        AmountInput.LineEditDisabled = !active;
        AmountInput.SetButtonDisabled(!active);
        WithdrawButton.Disabled = !active || _state == null || AmountInput.Value > _state.Balance;
    }
}
