using Content.Client.Shuttles.UI;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ReadOnlyBluespaceMapWindow : FancyWindow
{
    public ReadOnlyBluespaceMapWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Setup(EntityUid entity)
    {
        Map.Visible = true;
        Map.SetupReadOnlyMap(entity);
    }
}
