- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # Exodus 10 hours
  canBeAntag: true
  icon: "JobIconMercenary"
  supervisors: job-supervisors-hire
  weight: 3 # Prioritize station & department jobs
  displayWeight: 20 # Second from the bottom
  setPreference: true # Exodus keep Mercenary selectable
  access:
  - Mercenary
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
