- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 14400 # Exodus 4 hours
  icon: "JobIconPilot"
  supervisors: job-supervisors-hire
  weight: 2 # Prioritize station & department jobs
  displayWeight: 30 # Second from the top
  # Exodus: retain the existing selectable role (setPreference defaults to true).
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: SurgerySpeedModifier
        SpeedModifier: 1.25
