using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Casino;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.Casino;

[GenerateTypedNameReferences]
public sealed partial class RouletteWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public event Action<RouletteBet, uint>? BetPlaced;

    private RouletteUiState? _state;
    private bool _requestPending;

    public RouletteWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateBetTypes();
        NumberInput.IsValid = value => value is >= 0 and <= 36;
        NumberInput.InitDefaultButtons();
        AmountInput.IsValid = IsAmountValid;
        AmountInput.InitDefaultButtons();
        BetTypeSelector.OnItemSelected += args =>
        {
            BetTypeSelector.SelectId(args.Id);
            NumberRow.Visible = (RouletteBetType) args.Id == RouletteBetType.Number;
        };
        PlaceBetButton.OnPressed += _ => TryPlaceBet();
    }

    public void UpdateState(RouletteUiState state)
    {
        _state = state;
        Wheel.SetState(state.Phase, state.PhaseStartedAt, state.PhaseEndsAt, state.WinningNumber, state.RoundId);
        BalanceLabel.Text = Loc.GetString("roulette-balance", ("amount", state.Balance));
        TotalBetLabel.Text = Loc.GetString("roulette-total-bet", ("amount", state.TotalBet));
        ResultLabel.Text = state.Phase == RoulettePhase.Payout && state.WinningNumber >= 0
            ? Loc.GetString("roulette-result", ("number", state.WinningNumber))
            : Loc.GetString("roulette-result-pending");
        ErrorLabel.Text = state.LastPayout > 0
            ? Loc.GetString("roulette-payout", ("amount", state.LastPayout))
            : string.Empty;
        BettingDurationLabel.Text = Loc.GetString("roulette-rule-betting",
            ("seconds", (int) Math.Ceiling(state.BettingDuration.TotalSeconds)));
        SpinDurationLabel.Text = Loc.GetString("roulette-rule-spinning",
            ("seconds", (int) Math.Ceiling(state.SpinDuration.TotalSeconds)));
        PayoutDurationLabel.Text = Loc.GetString("roulette-rule-payout",
            ("seconds", (int) Math.Ceiling(state.PayoutDuration.TotalSeconds)));
        if (!IsAmountValid(AmountInput.Value))
            AmountInput.Value = state.MinimumBet;
        RebuildBets(state.Bets);
        RebuildPlayerBets(state.PlayerBets);
        UpdateControls();
    }

    public void SetRequestPending(bool pending)
    {
        _requestPending = pending;
        UpdateControls();
    }

    public void ShowError(RouletteBetError error)
    {
        ErrorLabel.Text = Loc.GetString(GetErrorLocId(error));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state == null)
            return;

        var remaining = _state.PhaseEndsAt - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        TimerLabel.Text = Loc.GetString("roulette-timer", ("seconds", (int) Math.Ceiling(remaining.TotalSeconds)));
        PhaseLabel.Text = Loc.GetString(GetPhaseLocId(_state.Phase));
        UpdateControls();
    }

    private void PopulateBetTypes()
    {
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-number"), (int) RouletteBetType.Number);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-red"), (int) RouletteBetType.Red);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-black"), (int) RouletteBetType.Black);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-even"), (int) RouletteBetType.Even);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-odd"), (int) RouletteBetType.Odd);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-low"), (int) RouletteBetType.Low);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-high"), (int) RouletteBetType.High);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-first-dozen"), (int) RouletteBetType.FirstDozen);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-second-dozen"), (int) RouletteBetType.SecondDozen);
        BetTypeSelector.AddItem(Loc.GetString("roulette-bet-third-dozen"), (int) RouletteBetType.ThirdDozen);
        BetTypeSelector.SelectId((int) RouletteBetType.Number);
    }

    private void TryPlaceBet()
    {
        if (_state == null || _state.Phase != RoulettePhase.Betting || _requestPending)
            return;

        var type = (RouletteBetType) BetTypeSelector.SelectedId;
        var number = type == RouletteBetType.Number ? NumberInput.Value : -1;
        BetPlaced?.Invoke(new RouletteBet(type, number, AmountInput.Value), _state.RoundId);
    }

    private void RebuildBets(RouletteBet[] bets)
    {
        BetsList.RemoveAllChildren();
        if (bets.Length == 0)
        {
            BetsList.AddChild(new Label { Text = Loc.GetString("roulette-no-bets") });
            return;
        }

        for (var i = 0; i < bets.Length; i++)
        {
            var bet = bets[i];
            var target = bet.Type == RouletteBetType.Number
                ? Loc.GetString("roulette-bet-number-value", ("number", bet.Number))
                : Loc.GetString(GetBetTypeLocId(bet.Type));
            BetsList.AddChild(new Label
            {
                Text = Loc.GetString("roulette-bet-entry", ("target", target), ("amount", bet.Amount))
            });
        }
    }

    private void UpdateControls()
    {
        var bettingOpen = _state?.Phase == RoulettePhase.Betting && _timing.CurTime < _state.PhaseEndsAt;
        PlaceBetButton.Disabled = !bettingOpen || _requestPending || !IsAmountValid(AmountInput.Value);
        BetTypeSelector.Disabled = !bettingOpen || _requestPending;
        NumberInput.LineEditDisabled = !bettingOpen || _requestPending;
        NumberInput.SetButtonDisabled(!bettingOpen || _requestPending);
        AmountInput.LineEditDisabled = !bettingOpen || _requestPending;
        AmountInput.SetButtonDisabled(!bettingOpen || _requestPending);
    }

    private bool IsAmountValid(int amount)
    {
        return _state != null &&
               amount >= _state.MinimumBet &&
               amount <= Math.Min(_state.Balance, _state.MaximumBet - _state.TotalBet) &&
               _state.Bets.Length < _state.MaximumBetsPerPlayer;
    }

    private void RebuildPlayerBets(RoulettePlayerBetSummary[] playerBets)
    {
        PlayerBetsList.RemoveAllChildren();
        if (playerBets.Length == 0)
        {
            PlayerBetsList.AddChild(new Label { Text = Loc.GetString("roulette-no-player-bets") });
            return;
        }

        for (var i = 0; i < playerBets.Length; i++)
        {
            var playerBet = playerBets[i];
            PlayerBetsList.AddChild(new Label
            {
                Text = Loc.GetString("roulette-player-bet-entry",
                    ("player", playerBet.PlayerName),
                    ("amount", playerBet.TotalBet))
            });
        }
    }

    private static string GetPhaseLocId(RoulettePhase phase)
    {
        return phase switch
        {
            RoulettePhase.Betting => "roulette-phase-betting",
            RoulettePhase.Spinning => "roulette-phase-spinning",
            RoulettePhase.Payout => "roulette-phase-payout",
            _ => "roulette-phase-betting"
        };
    }

    private static string GetBetTypeLocId(RouletteBetType type)
    {
        return type switch
        {
            RouletteBetType.Number => "roulette-bet-number",
            RouletteBetType.Red => "roulette-bet-red",
            RouletteBetType.Black => "roulette-bet-black",
            RouletteBetType.Even => "roulette-bet-even",
            RouletteBetType.Odd => "roulette-bet-odd",
            RouletteBetType.Low => "roulette-bet-low",
            RouletteBetType.High => "roulette-bet-high",
            RouletteBetType.FirstDozen => "roulette-bet-first-dozen",
            RouletteBetType.SecondDozen => "roulette-bet-second-dozen",
            RouletteBetType.ThirdDozen => "roulette-bet-third-dozen",
            _ => "roulette-bet-number"
        };
    }

    private static string GetErrorLocId(RouletteBetError error)
    {
        return error switch
        {
            RouletteBetError.BettingClosed => "roulette-error-betting-closed",
            RouletteBetError.InvalidBet => "roulette-error-invalid-bet",
            RouletteBetError.InsufficientFunds => "roulette-error-insufficient-funds",
            RouletteBetError.DuplicateRequest => "roulette-error-duplicate-request",
            RouletteBetError.AccountUnavailable => "roulette-error-account-unavailable",
            RouletteBetError.LimitExceeded => "roulette-error-limit-exceeded",
            RouletteBetError.TooManyBets => "roulette-error-too-many-bets",
            _ => "roulette-error-invalid-bet"
        };
    }
}
