using Content.Client.Message;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Monitor;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.Monitor.UI.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SensorInfo : BoxContainer
{
    public Action<string, AtmosMonitorThresholdType, AtmosAlarmThreshold, Gas?>? OnThresholdUpdate;
    public event Action<AtmosSensorData>? SensorDataCopied;
    private string _address;

    private ThresholdControl _pressureThreshold;
    private ThresholdControl _temperatureThreshold;
    // Exodus: gas rows and the current sensor snapshot are managed in SensorInfo.Exodus.cs.
    private Button _copySettings => CCopySettings;

    public SensorInfo(AtmosSensorData data, string address)
    {
        RobustXamlLoader.Load(this);

        _address = address;

        SensorAddress.Title = $"{address} : {Loc.GetString("air-alarm-ui-window-alarm-type", ("type", $"{data.AlarmState}"))}"; // Exodus-Localization

        AlarmStateLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-alarm-state-indicator",
                    ("color", AirAlarmWindow.ColorForAlarm(data.AlarmState)),
                    ("state", Loc.GetString("air-alarm-ui-window-alarm-type", ("type", $"{data.AlarmState}"))))); // Exodus-Localization
        PressureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-pressure-indicator",
                    ("color", AirAlarmWindow.ColorForThreshold(data.Pressure, data.PressureThreshold)),
                    ("pressure", $"{data.Pressure:0.##}")));
        TemperatureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-temperature-indicator",
                ("color", AirAlarmWindow.ColorForThreshold(data.Temperature, data.TemperatureThreshold)),
                ("tempC", $"{TemperatureHelpers.KelvinToCelsius(data.Temperature):0.#}"),
                ("temperature", $"{data.Temperature:0.##}")));

        InitializeGasControls(data); // Exodus: tolerate missing gas thresholds.

        _pressureThreshold = new ThresholdControl(Loc.GetString("air-alarm-ui-thresholds-pressure-title"), data.PressureThreshold, AtmosMonitorThresholdType.Pressure);
        PressureThresholdContainer.AddChild(_pressureThreshold);
        _temperatureThreshold = new ThresholdControl(Loc.GetString("air-alarm-ui-thresholds-temperature-title"),
            data.TemperatureThreshold,
            AtmosMonitorThresholdType.Temperature);
        TemperatureThresholdContainer.AddChild(_temperatureThreshold);

        _pressureThreshold.ThresholdDataChanged += (type, threshold, arg3) =>
        {
            OnThresholdUpdate?.Invoke(_address, type, threshold, arg3);
        };

        _temperatureThreshold.ThresholdDataChanged += (type, threshold, arg3) =>
        {
            OnThresholdUpdate?.Invoke(_address, type, threshold, arg3);
        };

        _copySettings.OnPressed += _ =>
        {
            SensorDataCopied?.Invoke(_data); // Exodus: copy the latest received settings.
        };
    }

    public void ChangeData(AtmosSensorData data)
    {
        SensorAddress.Title = $"{_address} : {Loc.GetString("air-alarm-ui-window-alarm-type", ("type", $"{data.AlarmState}"))}"; // Exodus-Localization

        AlarmStateLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-alarm-state-indicator",
                    ("color", AirAlarmWindow.ColorForAlarm(data.AlarmState)),
                    ("state", Loc.GetString("air-alarm-ui-window-alarm-type", ("type", $"{data.AlarmState}"))))); // Exodus-Localization

        PressureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-pressure-indicator",
                    ("color", AirAlarmWindow.ColorForThreshold(data.Pressure, data.PressureThreshold)),
                    ("pressure", $"{data.Pressure:0.##}")));
        TemperatureLabel.SetMarkup(Loc.GetString("air-alarm-ui-window-temperature-indicator",
                ("color", AirAlarmWindow.ColorForThreshold(data.Temperature, data.TemperatureThreshold)),
                ("tempC", $"{TemperatureHelpers.KelvinToCelsius(data.Temperature):0.#}"),
                ("temperature", $"{data.Temperature:0.##}")));

        UpdateGasData(data); // Exodus: reconcile gas readings and threshold controls.

        _pressureThreshold.UpdateThresholdData(data.PressureThreshold, data.Pressure);
        _temperatureThreshold.UpdateThresholdData(data.TemperatureThreshold, data.Temperature);
    }

 }
