using System.Text;
using Content.Client._Exodus.Guidebook.RichText;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._Exodus.Guidebook;

/// <summary>
/// Searches the articles exposed by the current guidebook, retaining results while an article is read.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GuidebookSearchControl : BoxContainer
{
    [Dependency] private IResourceManager _resources = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IGameTiming _timing = default!;

    private const int IndexBatchSize = 8;
    private const int ResultsPerPage = 30;
    private const string ResultButtonClass = "GuidebookSearchResult";
    private static readonly TimeSpan SearchDelay = TimeSpan.FromMilliseconds(150);
    private static readonly TimeSpan IndexFrameBudget = TimeSpan.FromMilliseconds(2);

    private readonly List<SearchEntry> _entries = new();
    private readonly Dictionary<string, string> _reagentGroupNames = new();
    private readonly List<(SearchEntry Entry, int Rank)> _matches = new();
    private readonly List<(ProtoId<GuideEntryPrototype> Id, ContainerButton Button)> _buttons = new();
    private readonly ISawmill _sawmill;
    private string _query = string.Empty;
    private ProtoId<GuideEntryPrototype>? _selected;
    private int _indexedCount;
    private bool _searchPending;
    private bool _openFirstResult;
    private TimeSpan _nextSearch;

    public event Action<bool>? OnSearchStateChanged;
    public event Action<ProtoId<GuideEntryPrototype>>? OnEntrySelected;

    public GuidebookSearchControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("guidebook.search");
        Stylesheet = CreateResultStylesheet(UserInterfaceManager.Stylesheet);

        Query.OnTextChanged += _ => SearchChanged();
        Query.OnTextEntered += _ =>
        {
            if (_searchPending)
            {
                _nextSearch = TimeSpan.Zero;
                _openFirstResult = true;
            }
            else if (_matches.Count > 0)
                OnEntrySelected?.Invoke(_matches[0].Entry.Id);
        };
        Clear.OnPressed += _ =>
        {
            Query.SetText(string.Empty, invokeEvent: true);
            Query.GrabKeyboardFocus();
        };
        More.OnPressed += _ => AddResults();
    }

    private static Stylesheet CreateResultStylesheet(Stylesheet? inherited)
    {
        var rules = new List<StyleRule>();
        if (inherited != null)
            rules.AddRange(inherited.Rules);

        AddResultStyle(rules, ContainerButton.StylePseudoClassNormal, "#262A32", "#464E5F");
        AddResultStyle(rules, ContainerButton.StylePseudoClassHover, "#343D4B", "#6683A0");
        AddResultStyle(rules, ContainerButton.StylePseudoClassPressed, "#2E435C", "#84ACD0");
        AddResultStyle(rules, ContainerButton.StylePseudoClassDisabled, "#23262B", "#464E5F");
        return new Stylesheet(rules);
    }

    private static void AddResultStyle(List<StyleRule> rules, string state, string background, string border)
    {
        rules.Add(Element<ContainerButton>().Class(ResultButtonClass).Pseudo(state)
            .Prop(ContainerButton.StylePropertyStyleBox, new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex(background),
                BorderColor = Color.FromHex(border),
                BorderThickness = new Thickness(1),
            })
            .Prop(Control.StylePropertyModulateSelf, Color.White));
    }

    /// <summary>
    /// Rebuilds the index when the window's article set changes. Using tree items preserves rules filtering
    /// and the restricted article sets opened by item help. Text is read lazily on the first search.
    /// </summary>
    public void SetEntries(IEnumerable<TreeItem> items)
    {
        _entries.Clear();
        _reagentGroupNames.Clear();
        _indexedCount = 0;
        _selected = null;

        foreach (var item in items)
        {
            if (item.Metadata is not GuideEntry guide)
                continue;

            var parents = new Stack<string>();
            for (var parent = item.Parent; parent != null; parent = parent.Parent)
            {
                if (parent is TreeItem { Metadata: GuideEntry parentGuide })
                    parents.Push(Loc.GetString(parentGuide.Name));
            }

            var title = Loc.GetString(guide.Name);
            _entries.Add(new SearchEntry(guide.Id, title, string.Join(" › ", parents), guide.Text));
        }

        Query.Text = string.Empty;
        SearchChanged();
    }

    public void SelectEntry(ProtoId<GuideEntryPrototype> id)
    {
        _selected = id;
        foreach (var (entryId, button) in _buttons)
            button.Pressed = entryId == id;
    }

    private void SearchChanged()
    {
        _query = GuidebookSearchText.Normalize(Query.Text);
        var searching = _query.Length > 0;
        _searchPending = searching;
        _openFirstResult = false;
        _nextSearch = _timing.RealTime + SearchDelay;
        _matches.Clear();
        _buttons.Clear();
        Results.DisposeAllChildren();
        More.Visible = false;
        Clear.Disabled = Query.Text.Length == 0;
        Status.Visible = searching;
        ResultsScroll.Visible = searching;
        VerticalExpand = searching;
        ResultsScroll.SetScrollValue(default);
        SetStatus("exodus-guidebook-search-searching");
        OnSearchStateChanged?.Invoke(searching);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!VisibleInTree || !_searchPending || _timing.RealTime < _nextSearch)
            return;

        // Bound first-search work per frame. Never render guide controls just to index their text.
        var end = Math.Min(_indexedCount + IndexBatchSize, _entries.Count);
        var deadline = _timing.RealTime + IndexFrameBudget;
        while (_indexedCount < end)
        {
            var entry = _entries[_indexedCount++];
            try
            {
                using var reader = _resources.ContentFileReadText(entry.Resource);
                entry.Text = GuidebookSearchText.Extract(
                    reader.ReadToEnd(), ResolveReagentName, ResolveReagentGroupNames, ResolveMarkupText);
                entry.NormalizedText = GuidebookSearchText.Normalize(entry.Text);
            }
            catch (Exception e)
            {
                // A missing or malformed page should not prevent searching the other articles or its title.
                _sawmill.Error($"Failed to index guide document {entry.Id}: {e}");
            }

            if (_timing.RealTime >= deadline)
                break;
        }

        if (_indexedCount < _entries.Count)
            return;

        _searchPending = false;
        foreach (var entry in _entries)
        {
            var rank = GuidebookSearchText.GetMatchRank(entry.NormalizedTitle, entry.NormalizedText, _query);
            if (rank >= 0)
                _matches.Add((entry, rank));
        }

        _matches.Sort(static (left, right) =>
        {
            var rank = left.Rank.CompareTo(right.Rank);
            if (rank != 0)
                return rank;

            var title = string.Compare(left.Entry.Title, right.Entry.Title, StringComparison.CurrentCulture);
            return title != 0 ? title : left.Entry.Id.CompareTo(right.Entry.Id);
        });
        SetStatus(_matches.Count == 0 ? "exodus-guidebook-search-empty" : "exodus-guidebook-search-count");
        AddResults();

        if (_openFirstResult && _matches.Count > 0)
            OnEntrySelected?.Invoke(_matches[0].Entry.Id);
        _openFirstResult = false;
    }

    private string? ResolveMarkupText(MarkupNode node)
    {
        return node.Name == "geneticmutation" ? GeneticMutationTag.GetText(node, _prototypes) : null;
    }

    private string? ResolveReagentName(ProtoId<ReagentPrototype> id)
    {
        return _prototypes.TryIndex(id, out var reagent) ? reagent.LocalizedName : null;
    }

    private string ResolveReagentGroupNames(string group)
    {
        if (_reagentGroupNames.TryGetValue(group, out var names))
            return names;

        // Expand only groups used by available articles, once per index, with the same membership as the cards.
        var builder = new StringBuilder();
        foreach (var reagent in _prototypes.EnumeratePrototypes<ReagentPrototype>())
        {
            if (reagent.Group != group)
                continue;

            builder.Append(reagent.LocalizedName).Append('\n');
        }

        names = builder.ToString();
        _reagentGroupNames.Add(group, names);
        return names;
    }

    private void SetStatus(string key)
    {
        Status.Text = Loc.GetString(key, ("count", _matches.Count));
        Status.ToolTip = Status.Text;
    }

    private void AddResults()
    {
        var end = Math.Min(_buttons.Count + ResultsPerPage, _matches.Count);
        for (var i = _buttons.Count; i < end; i++)
        {
            var entry = _matches[i].Entry;
            var button = new ContainerButton
            {
                ToggleMode = true,
                Pressed = _selected == entry.Id,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
                ToolTip = entry.Path.Length == 0 ? entry.Title : entry.Path + " › " + entry.Title,
            };
            button.AddStyleClass(ResultButtonClass);
            var contents = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                MouseFilter = MouseFilterMode.Ignore,
                Margin = new Thickness(4),
            };
            contents.AddChild(MakeLabel(entry.Title, Color.LightSkyBlue));
            if (entry.Path.Length > 0)
            {
                contents.AddChild(new Label
                {
                    Text = entry.Path,
                    ClipText = true,
                    FontColorOverride = Color.FromHex("#C0CAD8"),
                    MouseFilter = MouseFilterMode.Ignore,
                });
            }

            var snippet = GuidebookSearchText.GetSnippet(entry.Text, _query);
            if (snippet.Length > 0)
                contents.AddChild(MakeLabel(snippet));

            button.AddChild(contents);
            button.OnPressed += _ =>
            {
                SelectEntry(entry.Id);
                OnEntrySelected?.Invoke(entry.Id);
            };
            Results.AddChild(button);
            _buttons.Add((entry.Id, button));
        }

        More.Visible = _buttons.Count < _matches.Count;
    }

    private RichTextLabel MakeLabel(string text, Color? color = null)
    {
        text = GuidebookSearchText.CollapseWhitespace(text);
        var label = new RichTextLabel { HorizontalExpand = true, MouseFilter = MouseFilterMode.Ignore };
        var message = new FormattedMessage();
        var normalized = GuidebookSearchText.Normalize(text);
        var start = 0;
        while (start < text.Length)
        {
            var match = normalized.IndexOf(_query, start, StringComparison.Ordinal);
            if (match < 0)
            {
                message.AddText(text[start..]);
                break;
            }

            message.AddText(text[start..match]);
            message.PushColor(Color.Yellow);
            message.AddText(text.Substring(match, _query.Length));
            message.Pop();
            start = match + _query.Length;
        }

        label.SetMessage(message, color ?? Color.White);
        return label;
    }

    private sealed class SearchEntry(ProtoId<GuideEntryPrototype> id, string title, string path, ResPath resource)
    {
        public readonly ProtoId<GuideEntryPrototype> Id = id;
        public readonly string Title = title;
        public readonly string NormalizedTitle = GuidebookSearchText.Normalize(title);
        public readonly string Path = path;
        public readonly ResPath Resource = resource;
        public string Text = string.Empty;
        public string NormalizedText = string.Empty;
    }
}
