using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared._Exodus.Territory;
using Content.Shared._Exodus.War;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Exodus.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunicationsConsoleMenu : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _entitySystems = default!;

    private readonly SpriteSystem _sprites;
    private readonly VScrollBar? _messageScrollBar;

    private readonly Dictionary<ProtoId<TerritoryFactionPrototype>, WarDeclarationRow> _warRows = new();
    private readonly HashSet<ProtoId<TerritoryFactionPrototype>> _seenWarTargets = new();
    private readonly List<ProtoId<TerritoryFactionPrototype>> _staleWarTargets = new();
    private readonly FactionRelationMap _relationMap = new();
    private readonly List<(Control Control, string Search)> _corporationRows = new();

    private bool _warCodeAllowsWar;
    private string _warSourceName = string.Empty;
    private long _lastWarCountdownSecond = long.MinValue;
    private bool _hasWarState;
    private bool _warRoundRunning;
    private bool _factionLayout;
    private TimeSpan _allianceBreakCooldown;
    private WarDeclarationConsoleState? _warState;
    private FactionAlertLevelState? _factionAlerts;
    private string _sectorLevel = string.Empty;
    private string? _pendingSector;
    private TimeSpan _pendingSectorAt;
    private Color _sectorColor = Color.White;
    private Color _shownSectorColor;
    private Color _shownFactionColor;
    private bool _sectorColorReady;
    private bool _factionColorReady;

    public OptionButton FactionAlertLevelButton => FactionDashboard.FactionAlertLevelButton;

    public bool CanAnnounce;
    public bool CanBroadcast;
    public bool AlertLevelSelectable;
    public string CurrentLevel = string.Empty;

    public event Action<string>? OnAlertLevel;
    public event Action<string>? OnFactionAlertLevel;
    public event Action<string>? OnAnnounce;
    public event Action<string>? OnBroadcast;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnDeclareWar;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnOfferPeace;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnAcceptPeace;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnWithdrawPeace;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnOfferAlliance;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnAcceptAlliance;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnWithdrawAlliance;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnBreakAlliance;

    public CommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        _sprites = _entitySystems.GetEntitySystem<SpriteSystem>();
        RobustXamlLoader.Load(this);
        foreach (var child in MessageInput.Children)
        {
            if (child is VScrollBar scrollBar)
                _messageScrollBar = scrollBar;
        }
        FactionDashboard.RelationMapHost.AddChild(_relationMap);
        FactionDashboard.CorporationSearch.OnTextChanged += _ =>
        {
            FilterCorporations();
            FactionDashboard.CorporationScroll.VScroll = 0;
        };
        FactionDashboard.Tabs.OnTabChanged += _ => ResetWarConfirmations();

        MessageInput.Placeholder = new Rope.Leaf(_loc.GetString("comms-console-menu-announcement-placeholder"));

        MessageInput.OnTextChanged += _ => UpdateAnnouncementAvailability();

        AnnounceButton.OnPressed += _ => OnAnnounce?.Invoke(Rope.Collapse(MessageInput.TextRope));
        AnnounceButton.Disabled = !CanAnnounce;

        BroadcastButton.OnPressed += _ => OnBroadcast?.Invoke(Rope.Collapse(MessageInput.TextRope));
        BroadcastButton.Disabled = !CanBroadcast;

        AlertLevelButton.OnItemSelected += args =>
        {
            var metadata = AlertLevelButton.GetItemMetadata(args.Id);
            if (metadata is string cast)
                OnAlertLevel?.Invoke(cast);
        };

        FactionAlertLevelButton.OnItemSelected += args =>
        {
            var metadata = FactionAlertLevelButton.GetItemMetadata(args.Id);
            if (metadata is string cast)
                OnFactionAlertLevel?.Invoke(cast);
        };

        AlertLevelButton.Disabled = !AlertLevelSelectable;
        FactionDashboard.SectorColorBar.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.White };
        FactionDashboard.FactionColorBar.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.White };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWarAvailability();
        UpdateWarConfirmationAppearance();
        if (_factionLayout && _messageScrollBar != null)
            _messageScrollBar.Visible = _messageScrollBar.MaxValue > _messageScrollBar.Page;
    }

    public void UpdateSectorCode(string currentLevel, string? pendingLevel, TimeSpan pendingAt, Color color)
    {
        _sectorLevel = currentLevel;
        _pendingSector = pendingLevel;
        _pendingSectorAt = pendingAt;
        _sectorColor = color == default ? Color.White : color;
        _lastWarCountdownSecond = long.MinValue;
    }

    public void UpdateFactionAlerts(FactionAlertLevelState? state)
    {
        var previous = _factionAlerts;
        _factionAlerts = state;
        _lastWarCountdownSecond = long.MinValue;
        FactionAlertLevelButton.Visible = state != null;
        FactionDashboard.FactionCodeCard.Visible = state != null;
        if (state != null && previous != null && state.CurrentLevel == previous.CurrentLevel &&
            SameEntries(state.Levels, previous.Levels))
        {
            return;
        }

        FactionAlertLevelButton.Clear();
        if (state == null)
            return;

        foreach (var level in state.Levels)
        {
            FactionAlertLevelButton.AddItem(Loc.GetString(level.Name));
            FactionAlertLevelButton.SetItemMetadata(FactionAlertLevelButton.ItemCount - 1, level.Id);
            FactionAlertLevelButton.SetItemDisabled(FactionAlertLevelButton.ItemCount - 1,
                !level.Selectable || level.Id == state.CurrentLevel);
            if (level.Id == state.CurrentLevel)
            {
                FactionAlertLevelButton.Select(FactionAlertLevelButton.ItemCount - 1);
            }
        }
    }

    private string AlertName(string alert)
    {
        return _loc.TryGetString($"alert-level-{alert}", out var name) ? name : alert;
    }

    public void UpdateAnnouncementAvailability()
    {
        var tooLong = MessageInput.TextLength > _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        var empty = string.IsNullOrWhiteSpace(Rope.Collapse(MessageInput.TextRope));
        AnnounceButton.Disabled = !CanAnnounce || tooLong || empty;
        AnnounceButton.ToolTip = tooLong ? Loc.GetString("comms-console-message-too-long") : null;
        if (!_factionLayout)
            return;

        BroadcastButton.Disabled = !CanBroadcast || tooLong || empty;
        FactionDashboard.MessageCounter.Text = Loc.GetString("faction-console-message-count",
            ("count", MessageInput.TextLength), ("max", _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength)));
        FactionDashboard.MessageCounter.FontColorOverride = tooLong ? Color.Salmon : Color.LightGray;
        FactionDashboard.MessageStatus.SetMessage(Loc.GetString(tooLong
            ? "comms-console-message-too-long"
            : empty ? "faction-console-message-empty"
            : !CanAnnounce ? "faction-console-message-cooldown" : "faction-console-message-ready"));
    }

    private static bool SameEntries<T>(List<T> first, List<T> second) where T : struct, IEquatable<T>
    {
        if (first.Count != second.Count)
            return false;

        for (var i = 0; i < first.Count; i++)
        {
            if (!first[i].Equals(second[i]))
                return false;
        }

        return true;
    }

    private static string FormatRemaining(TimeSpan duration)
    {
        var remaining = TimeSpan.FromSeconds(Math.Max(0, Math.Ceiling(duration.TotalSeconds)));
        return $"{(int)remaining.TotalHours:00}:{remaining.Minutes:00}:{remaining.Seconds:00}";
    }

    public void UpdateAlertLevels(List<string>? alerts, string currentAlert)
    {
        AlertLevelButton.Clear();

        if (alerts == null)
        {
            AlertLevelButton.AddItem(AlertName(currentAlert));
            AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, currentAlert);
        }
        else
        {
            if (!alerts.Contains(currentAlert))
            {
                AlertLevelButton.AddItem(AlertName(currentAlert));
                AlertLevelButton.SetItemMetadata(0, currentAlert);
                AlertLevelButton.SetItemDisabled(0, true);
            }

            foreach (var alert in alerts)
            {
                AlertLevelButton.AddItem(AlertName(alert));
                AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, alert);
                if (alert == currentAlert)
                    AlertLevelButton.Select(AlertLevelButton.ItemCount - 1);
            }
        }
    }
}
