using Content.Client.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared._Exodus.Territory;
using Content.Shared._Exodus.War;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Exodus.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunicationsConsoleMenu : FancyWindow
{
    private static readonly Color WarConfirmationTextColor = Color.FromHex("#909090");

    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly Dictionary<ProtoId<TerritoryFactionPrototype>, WarDeclarationRow> _warRows = new();
    private readonly HashSet<ProtoId<TerritoryFactionPrototype>> _seenWarTargets = new();
    private readonly List<ProtoId<TerritoryFactionPrototype>> _staleWarTargets = new();

    private TimeSpan _warAvailableAt;
    private string _warSourceName = string.Empty;
    private long _lastWarCountdownSecond = long.MinValue;
    private bool _hasWarState;
    private bool _warRoundRunning;

    public bool CanAnnounce;
    public bool CanBroadcast;
    public bool AlertLevelSelectable;
    public string CurrentLevel = string.Empty;

    public event Action<string>? OnAlertLevel;
    public event Action<string>? OnAnnounce;
    public event Action<string>? OnBroadcast;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnDeclareWar;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnOfferPeace;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnAcceptPeace;
    public event Action<ProtoId<TerritoryFactionPrototype>, int>? OnWithdrawPeace;

    public CommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessageInput.Placeholder = new Rope.Leaf(_loc.GetString("comms-console-menu-announcement-placeholder"));

        var maxAnnounceLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        MessageInput.OnTextChanged += (args) =>
        {
            if (args.Control.TextLength > maxAnnounceLength)
            {
                AnnounceButton.Disabled = true;
                AnnounceButton.ToolTip = Loc.GetString("comms-console-message-too-long");
            }
            else
            {
                AnnounceButton.Disabled = !CanAnnounce;
                AnnounceButton.ToolTip = null;
            }
        };

        AnnounceButton.OnPressed += _ => OnAnnounce?.Invoke(Rope.Collapse(MessageInput.TextRope));
        AnnounceButton.Disabled = !CanAnnounce;

        BroadcastButton.OnPressed += _ => OnBroadcast?.Invoke(Rope.Collapse(MessageInput.TextRope));
        BroadcastButton.Disabled = !CanBroadcast;

        AlertLevelButton.OnItemSelected += args =>
        {
            var metadata = AlertLevelButton.GetItemMetadata(args.Id);
            if (metadata != null && metadata is string cast)
            {
                OnAlertLevel?.Invoke(cast);
            }
        };

        AlertLevelButton.Disabled = !AlertLevelSelectable;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWarAvailability();
        UpdateWarConfirmationAppearance();
    }

    public void UpdateWarState(WarDeclarationConsoleState? state)
    {
        _hasWarState = state != null;
        WarSection.Visible = _hasWarState;
        _lastWarCountdownSecond = long.MinValue;

        if (state == null)
        {
            ClearWarRows();
            return;
        }

        _warAvailableAt = state.AvailableAt;
        _warSourceName = Loc.GetString(state.SourceName);
        _warRoundRunning = state.RoundRunning;
        _seenWarTargets.Clear();

        var incomingOffers = 0;
        foreach (var target in state.Targets)
        {
            if (!_seenWarTargets.Add(target.Faction))
                continue;

            if (!_warRows.TryGetValue(target.Faction, out var row))
            {
                row = CreateWarRow(target.Faction);
                _warRows.Add(target.Faction, row);
                WarRows.AddChild(row.Container);
            }

            UpdateWarRow(row, target);
            if (target.PeaceDirection == PeaceOfferDirection.Incoming)
                incomingOffers++;
        }

        WarHeading.Title = incomingOffers == 0
            ? Loc.GetString("war-declaration-console-title")
            : Loc.GetString("war-declaration-console-title-pending", ("count", incomingOffers));

        _staleWarTargets.Clear();
        foreach (var faction in _warRows.Keys)
        {
            if (!_seenWarTargets.Contains(faction))
                _staleWarTargets.Add(faction);
        }

        foreach (var faction in _staleWarTargets)
        {
            var row = _warRows[faction];
            row.Container.Dispose();
            _warRows.Remove(faction);
        }

        UpdateWarAvailability();
    }

    private WarDeclarationRow CreateWarRow(ProtoId<TerritoryFactionPrototype> faction)
    {
        var status = new Label
        {
            HorizontalExpand = true,
        };
        var button = new ConfirmButton
        {
            HorizontalExpand = true,
            ResetTime = TimeSpan.FromSeconds(5),
            CooldownTime = TimeSpan.FromSeconds(0.75),
        };
        button.StyleClasses.Add(StyleNano.StyleClassButtonColorRed);
        button.OnPressed += _ => OnDeclareWar?.Invoke(faction);

        var detail = new Label { HorizontalExpand = true };
        var offerButton = new Button
        {
            HorizontalExpand = true,
            Text = Loc.GetString("war-peace-offer-button"),
        };
        var acceptButton = new ConfirmButton
        {
            HorizontalExpand = true,
            ResetTime = TimeSpan.FromSeconds(5),
            CooldownTime = TimeSpan.FromSeconds(0.75),
            Text = Loc.GetString("war-peace-accept-button"),
        };
        var withdrawButton = new Button
        {
            HorizontalExpand = true,
            Text = Loc.GetString("war-peace-withdraw-button"),
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        container.AddChild(status);
        container.AddChild(detail);
        container.AddChild(button);
        container.AddChild(offerButton);
        container.AddChild(acceptButton);
        container.AddChild(withdrawButton);

        var row = new WarDeclarationRow(container, status, detail, button, offerButton, acceptButton, withdrawButton);
        offerButton.OnPressed += _ => OnOfferPeace?.Invoke(faction);
        acceptButton.OnPressed += _ => OnAcceptPeace?.Invoke(faction, row.PeaceOfferId);
        withdrawButton.OnPressed += _ => OnWithdrawPeace?.Invoke(faction, row.PeaceOfferId);
        return row;
    }

    private void UpdateWarRow(WarDeclarationRow row, WarDeclarationTargetState target)
    {
        var targetName = Loc.GetString(target.Name);
        if (row.Direction != target.Direction)
            ResetConfirmation(row.Button);

        if (row.PeaceOfferId != target.PeaceOfferId || row.PeaceDirection != target.PeaceDirection)
            ResetConfirmation(row.AcceptButton);

        row.TargetName = targetName;
        row.Direction = target.Direction;
        row.PeaceDirection = target.PeaceDirection;
        row.PeaceOfferId = target.PeaceOfferId;
        row.DeclarationAvailableAt = target.DeclarationAvailableAt;
        row.PeaceOfferAvailableAt = target.PeaceOfferAvailableAt;
        row.AcceptButton.ConfirmationText = Loc.GetString("war-peace-accept-confirm", ("target", targetName));
        var atWar = target.Direction != WarDeclarationDirection.None;
        row.OfferButton.Visible = atWar && target.PeaceDirection == PeaceOfferDirection.None;
        row.AcceptButton.Visible = atWar && target.PeaceDirection == PeaceOfferDirection.Incoming;
        row.WithdrawButton.Visible = atWar && target.PeaceDirection == PeaceOfferDirection.Outgoing;
        row.Button.ConfirmationText = Loc.GetString(
            "war-declaration-console-confirm",
            ("target", targetName));
        row.Button.Text = Loc.GetString(
            "war-declaration-console-button",
            ("target", targetName));

        switch (target.Direction)
        {
            case WarDeclarationDirection.None:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-cold",
                    ("target", targetName));
                row.Status.FontColorOverride = Color.CornflowerBlue;
                row.Button.Visible = true;
                break;
            case WarDeclarationDirection.Outgoing:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-declared",
                    ("source", _warSourceName),
                    ("target", targetName));
                row.Status.FontColorOverride = Color.Crimson;
                row.Button.Visible = false;
                break;
            case WarDeclarationDirection.Incoming:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-declared",
                    ("source", targetName),
                    ("target", _warSourceName));
                row.Status.FontColorOverride = Color.Crimson;
                row.Button.Visible = false;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    private void UpdateWarAvailability()
    {
        if (!_hasWarState)
            return;

        var now = _timing.CurTime;
        var currentSecond = (long) now.TotalSeconds;
        if (currentSecond == _lastWarCountdownSecond)
            return;

        _lastWarCountdownSecond = currentSecond;
        var secondsRemaining = (long) Math.Ceiling(Math.Max(0, (_warAvailableAt - now).TotalSeconds));
        var available = _warRoundRunning && secondsRemaining == 0;
        if (!_warRoundRunning)
        {
            WarUnlockLabel.Text = Loc.GetString("war-declaration-round-not-running");
            WarUnlockLabel.FontColorOverride = Color.Gray;
        }
        else if (available)
        {
            WarUnlockLabel.Text = Loc.GetString("war-declaration-console-available");
            WarUnlockLabel.FontColorOverride = Color.Lime;
        }
        else
        {
            var remaining = TimeSpan.FromSeconds(secondsRemaining);
            var time = $"{(int)remaining.TotalHours:00}:{remaining.Minutes:00}:{remaining.Seconds:00}";
            WarUnlockLabel.Text = Loc.GetString(
                "war-declaration-console-available-in",
                ("time", time));
            WarUnlockLabel.FontColorOverride = Color.Gold;
        }

        foreach (var row in _warRows.Values)
        {
            UpdateWarRowAvailability(row, now);
        }
    }

    private void UpdateWarRowAvailability(WarDeclarationRow row, TimeSpan now)
    {
        SetConfirmationAvailable(row.Button,
            _warRoundRunning && row.Button.Visible && now >= row.DeclarationAvailableAt);
        SetConfirmationAvailable(row.AcceptButton, _warRoundRunning && row.AcceptButton.Visible);
        row.OfferButton.Disabled = !_warRoundRunning || now < row.PeaceOfferAvailableAt;
        row.WithdrawButton.Disabled = !_warRoundRunning;
        row.Detail.Visible = true;
        row.Detail.FontColorOverride = Color.Gold;

        if (row.Direction == WarDeclarationDirection.None)
        {
            if (row.DeclarationAvailableAt > _warAvailableAt && now < row.DeclarationAvailableAt)
            {
                row.Detail.Text = Loc.GetString("war-declaration-post-war-cooldown",
                    ("time", FormatRemaining(row.DeclarationAvailableAt - now)));
            }
            else
            {
                row.Detail.Visible = false;
            }

            return;
        }

        switch (row.PeaceDirection)
        {
            case PeaceOfferDirection.Outgoing:
                row.Detail.Text = Loc.GetString("war-peace-status-outgoing", ("target", row.TargetName));
                break;
            case PeaceOfferDirection.Incoming:
                row.Detail.Text = Loc.GetString("war-peace-status-incoming", ("target", row.TargetName));
                break;
            default:
                if (now < row.PeaceOfferAvailableAt)
                {
                    row.Detail.Text = Loc.GetString("war-peace-offer-cooldown",
                        ("time", FormatRemaining(row.PeaceOfferAvailableAt - now)));
                }
                else
                {
                    row.Detail.Visible = false;
                }

                break;
        }
    }

    private static string FormatRemaining(TimeSpan duration)
    {
        var remaining = TimeSpan.FromSeconds(Math.Max(0, Math.Ceiling(duration.TotalSeconds)));
        return $"{(int)remaining.TotalHours:00}:{remaining.Minutes:00}:{remaining.Seconds:00}";
    }

    private static void ResetConfirmation(ConfirmButton button)
    {
        button.IsConfirming = false;
        button.Label.Text = button.Text;
        button.Disabled = true;
    }

    private static void SetConfirmationAvailable(ConfirmButton button, bool available)
    {
        if (!available)
        {
            ResetConfirmation(button);
        }
        else if (!button.IsConfirming)
        {
            button.Disabled = false;
        }
    }

    private void ClearWarRows()
    {
        foreach (var row in _warRows.Values)
        {
            row.Container.Dispose();
        }

        _warRows.Clear();
        _seenWarTargets.Clear();
        _staleWarTargets.Clear();
    }

    private void UpdateWarConfirmationAppearance()
    {
        foreach (var row in _warRows.Values)
        {
            row.Button.Label.FontColorOverride = row.Button.IsConfirming
                ? WarConfirmationTextColor
                : null;
            row.AcceptButton.Label.FontColorOverride = row.AcceptButton.IsConfirming
                ? WarConfirmationTextColor
                : null;
        }
    }

    // The current alert could make levels unselectable, so we need to ensure that the UI reacts properly.
    // If the current alert is unselectable, the only item in the alerts list will be
    // the current alert. Otherwise, it will be the list of alerts, with the current alert
    // selected.
    public void UpdateAlertLevels(List<string>? alerts, string currentAlert)
    {
        AlertLevelButton.Clear();

        if (alerts == null)
        {
            var name = currentAlert;
            if (Loc.TryGetString($"alert-level-{currentAlert}", out var locName))
            {
                name = locName;
            }
            AlertLevelButton.AddItem(name);
            AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, currentAlert);
        }
        else
        {
            foreach (var alert in alerts)
            {
                var name = alert;
                if (Loc.TryGetString($"alert-level-{alert}", out var locName))
                {
                    name = locName;
                }
                AlertLevelButton.AddItem(name);
                AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, alert);
                if (alert == currentAlert)
                {
                    AlertLevelButton.Select(AlertLevelButton.ItemCount - 1);
                }
            }
        }
    }

    private sealed class WarDeclarationRow(
        BoxContainer container,
        Label status,
        Label detail,
        ConfirmButton button,
        Button offerButton,
        ConfirmButton acceptButton,
        Button withdrawButton)
    {
        public BoxContainer Container { get; } = container;
        public Label Status { get; } = status;
        public Label Detail { get; } = detail;
        public ConfirmButton Button { get; } = button;
        public Button OfferButton { get; } = offerButton;
        public ConfirmButton AcceptButton { get; } = acceptButton;
        public Button WithdrawButton { get; } = withdrawButton;
        public string TargetName { get; set; } = string.Empty;
        public WarDeclarationDirection Direction { get; set; }
        public PeaceOfferDirection PeaceDirection { get; set; }
        public int PeaceOfferId { get; set; }
        public TimeSpan DeclarationAvailableAt { get; set; }
        public TimeSpan PeaceOfferAvailableAt { get; set; }
    }
}
