using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionConsoleDashboard : BoxContainer
{
    public FactionConsoleDashboard()
    {
        RobustXamlLoader.Load(this);
    }
}
