using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.MedicalTracking;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.MedicalTracking;

[GenerateTypedNameReferences]
public sealed partial class MedicalTrackingWindow : FancyWindow
{
    private MedicalTrackingState? _state;

    public MedicalTrackingWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Setup(EntityUid entity)
    {
        Map.Visible = true;
        Map.SetupReadOnlyMap(entity);
    }

    public void UpdateState(MedicalTrackingState state)
    {
        // Open tablets refresh to remove destroyed bodies, but unchanged lists do not rebuild controls.
        if (_state == null || !SameEntries(_state.Contacts, state.Contacts))
        {
            Map.SetMedicalContacts(state.Contacts);
            Contacts.DisposeAllChildren();
            foreach (var contact in state.Contacts)
            {
                var button = new Button
                {
                    Text = ContactText(contact),
                    ToolTip = Loc.GetString("medical-tracking-sampled", ("time", contact.UpdatedAt.ToString(@"hh\:mm\:ss"))),
                };
                button.OnPressed += _ => Map.FocusMedicalContact(contact.Coordinates);
                Contacts.AddChild(button);
            }

            if (state.Contacts.Count == 0)
                Contacts.AddChild(new Label { Text = Loc.GetString("medical-tracking-no-bodies") });
        }

        _state = state;
    }

    public static string ContactText(MedicalTrackingContact contact)
    {
        var status = Loc.GetString(contact.State switch
        {
            MobState.Alive => "medical-tracking-alive",
            MobState.Critical => "medical-tracking-critical",
            _ => "medical-tracking-dead",
        });
        return Loc.GetString("medical-tracking-contact", ("name", contact.Name), ("status", status),
            ("x", (int) contact.Coordinates.X), ("y", (int) contact.Coordinates.Y));
    }

    private static bool SameEntries<T>(List<T> left, List<T> right) where T : IEquatable<T>
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (!left[i].Equals(right[i]))
                return false;
        }

        return true;
    }
}
