using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.MedicalTracking;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.MedicalTracking;

[GenerateTypedNameReferences]
public sealed partial class MedicalTrackingWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    private MedicalTrackingState? _state;
    private NetEntity? _selected;
    private readonly List<MedicalTrackingContact> _visible = new();
    private readonly Dictionary<NetEntity, ContainerButton> _cards = new();
    private readonly List<(Label Label, TimeSpan Sample)> _ages = new();
    private TimeSpan _nextAgeUpdate;

    public MedicalTrackingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        StatusFilter.AddItem(Loc.GetString("medical-tracking-filter-all"), 0);
        StatusFilter.AddItem(Loc.GetString("medical-tracking-filter-critical"), (int) MobState.Critical);
        StatusFilter.AddItem(Loc.GetString("medical-tracking-filter-dead"), (int) MobState.Dead);
        StatusFilter.OnItemSelected += args =>
        {
            StatusFilter.SelectId(args.Id);
            Rebuild();
        };
        Search.OnTextChanged += _ => Rebuild();
        MyPosition.OnPressed += _ => Map.FocusMedicalOperator();
        ShowClients.OnPressed += _ => Map.ShowMedicalContacts();
        Map.MedicalContactSelected += SelectContact;
    }

    public void Setup(EntityUid entity)
    {
        Map.Visible = true;
        Map.SetupReadOnlyMap(entity);
    }

    public void UpdateState(MedicalTrackingState state)
    {
        // Do not rebuild cards on the one-second removal refresh if the sampled contacts are unchanged.
        var changed = _state == null || !SameEntries(_state.Contacts, state.Contacts);
        _state = state;
        if (changed)
            Rebuild();
    }

    private void Rebuild()
    {
        if (_state == null)
            return;

        _visible.Clear();
        var search = Search.Text.Trim();
        foreach (var contact in _state.Contacts)
        {
            if ((StatusFilter.SelectedId == 0 || StatusFilter.SelectedId == (int) contact.State) &&
                contact.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase))
                _visible.Add(contact);
        }

        _visible.Sort(static (left, right) =>
        {
            var priority = MedicalTrackingDisplay.Priority(left.State).CompareTo(MedicalTrackingDisplay.Priority(right.State));
            return priority != 0 ? priority : string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase);
        });
        Contacts.DisposeAllChildren();
        _cards.Clear();
        _ages.Clear();
        foreach (var contact in _visible)
        {
            var card = new ContainerButton { ToggleMode = true, Margin = new Thickness(0, 0, 0, 5) };
            card.AddStyleClass(ContainerButton.StyleClassButton);
            var content = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, MouseFilter = MouseFilterMode.Ignore, Margin = new Thickness(4) };
            var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, MouseFilter = MouseFilterMode.Ignore };
            header.AddChild(new Label { Text = contact.Name, ClipText = true, HorizontalExpand = true });
            header.AddChild(new Label { Text = Loc.GetString(contact.TierName), FontColorOverride = Color.LightGray });
            content.AddChild(header);
            content.AddChild(new Label { Text = MedicalTrackingDisplay.Status(contact.State), FontColorOverride = MedicalTrackingDisplay.StatusColor(contact.State) });
            content.AddChild(new Label { Text = Loc.GetString("medical-tracking-coordinates", ("x", (int) contact.Coordinates.X), ("y", (int) contact.Coordinates.Y)) });
            var age = new Label { FontColorOverride = Color.LightGray };
            content.AddChild(age);
            _ages.Add((age, contact.UpdatedAt));
            card.AddChild(content);
            card.ToolTip = contact.Name;
            card.OnPressed += _ => SelectContact(contact.Body);
            Contacts.AddChild(card);
            _cards.Add(contact.Body, card);
        }

        if (_selected is { } selected && !_cards.ContainsKey(selected))
            _selected = null;
        UpdateSelection();
        Map.SetMedicalContacts(_visible);
        ClientCount.Text = Loc.GetString("medical-tracking-bodies", ("shown", _visible.Count), ("total", _state.Contacts.Count));
        ShowClients.Disabled = _visible.Count == 0;
        if (_visible.Count == 0)
            Contacts.AddChild(new Label { Text = Loc.GetString(_state.Contacts.Count == 0 ? "medical-tracking-no-bodies" : "medical-tracking-no-matches") });
        UpdateAges();
    }

    private void SelectContact(NetEntity body)
    {
        foreach (var contact in _visible)
        {
            if (contact.Body != body)
                continue;

            _selected = body;
            UpdateSelection();
            Map.FocusMedicalContact(contact.Coordinates);
            return;
        }
    }

    private void UpdateSelection()
    {
        foreach (var (body, card) in _cards)
            card.Pressed = body == _selected;
        Map.SelectMedicalContact(_selected);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_timing.CurTime >= _nextAgeUpdate)
            UpdateAges();
    }

    private void UpdateAges()
    {
        var now = _timing.CurTime;
        _nextAgeUpdate = now + TimeSpan.FromSeconds(1);
        foreach (var (label, sample) in _ages)
            label.Text = Loc.GetString("medical-tracking-signal-age", ("seconds", Math.Max(0, (int) (now - sample).TotalSeconds)));
    }

    private static bool SameEntries<T>(List<T> left, List<T> right) where T : IEquatable<T>
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (!left[i].Equals(right[i]))
                return false;
        }

        return true;
    }
}
