using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.MedicalTracking;
using Content.Shared.Pinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.MedicalTracking;

[GenerateTypedNameReferences]
public sealed partial class MedicalTrackingPinpointerWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    public event Action<NetEntity?>? SelectTarget;

    private readonly EntityQuery<PinpointerComponent> _pointerQuery;
    private readonly Dictionary<NetEntity, MedicalTrackingBrainCard> _cards = new();
    private readonly HashSet<NetEntity> _received = new();
    private readonly List<NetEntity> _removed = new();
    private readonly List<MedicalTrackingBrain> _visible = new();
    private readonly List<NetEntity> _rowOrder = new();
    private readonly Label _empty = new() { ClipText = true, StyleClasses = { "MedicalMuted" } };
    private MedicalTrackingPinpointerState? _state;
    private EntityUid? _owner;
    private string? _signalKey;

    public MedicalTrackingPinpointerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _pointerQuery = _entityManager.GetEntityQuery<PinpointerComponent>();
        Stylesheet = MedicalTrackingUiTheme.CreateStylesheet(UserInterfaceManager.Stylesheet);
        ClearTarget.OnPressed += _ => RequestTarget(null);
        Search.OnTextChanged += _ => RefreshList(resetScroll: true);
        Brains.AddChild(_empty);
        UpdateState(new MedicalTrackingPinpointerState(new List<MedicalTrackingBrain>(), null));
    }

    public void Setup(EntityUid entity)
    {
        _owner = entity;
        Pointer.SetEntity(entity);
        UpdateSignal();
    }

    public void UpdateState(MedicalTrackingPinpointerState state)
    {
        var entriesChanged = !SameEntries(state);
        if (!entriesChanged && _state?.Target == state.Target)
            return;

        _state = state;
        if (!entriesChanged)
        {
            UpdateSelection();
            return;
        }

        // Keep controls and scroll position across updates, including while searching.
        _received.Clear();
        foreach (var brain in state.Brains)
        {
            _received.Add(brain.Entity);
            if (!_cards.TryGetValue(brain.Entity, out var card))
            {
                card = new MedicalTrackingBrainCard();
                var target = brain.Entity;
                card.OnPressed += _ => RequestTarget(target);
                _cards.Add(target, card);
                Brains.AddChild(card);
            }
            card.UpdateBrain(brain);
        }

        _removed.Clear();
        foreach (var target in _cards.Keys)
        {
            if (!_received.Contains(target))
                _removed.Add(target);
        }
        foreach (var target in _removed)
        {
            _cards[target].Dispose();
            _cards.Remove(target);
        }
        RefreshList();
    }

    private void RefreshList(bool resetScroll = false)
    {
        if (_state == null)
            return;

        _visible.Clear();
        var search = Search.Text.Trim();
        foreach (var brain in _state.Brains)
        {
            var visible = brain.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase);
            _cards[brain.Entity].Visible = visible;
            if (visible)
                _visible.Add(brain);
        }
        _visible.Sort(static (left, right) =>
        {
            var name = string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase);
            return name != 0 ? name : left.Entity.CompareTo(right.Entity);
        });
        var orderChanged = _rowOrder.Count != _visible.Count;
        for (var i = 0; !orderChanged && i < _visible.Count; i++)
            orderChanged = _rowOrder[i] != _visible[i].Entity;
        if (orderChanged)
        {
            _rowOrder.Clear();
            for (var i = 0; i < _visible.Count; i++)
            {
                var target = _visible[i].Entity;
                _rowOrder.Add(target);
                _cards[target].SetPositionInParent(i);
            }
        }
        _empty.Visible = _visible.Count == 0;
        _empty.Text = Loc.GetString(_state.Brains.Count == 0 ? "medical-tracking-no-brains" : "medical-tracking-no-matches");
        _empty.ToolTip = _empty.Text;
        ClientCount.Text = Loc.GetString("medical-tracking-count-compact", ("shown", _visible.Count), ("total", _state.Brains.Count));
        if (resetScroll)
            ClientScroll.VScrollTarget = 0;
        UpdateSelection();
    }

    private void RequestTarget(NetEntity? target)
    {
        if (_state?.Target != target)
            SelectTarget?.Invoke(target);
        // Selection is authoritative on the device and may be changed by another open window.
        UpdateSelection();
    }

    private void UpdateSelection()
    {
        foreach (var (target, card) in _cards)
            card.Pressed = target == _state?.Target;

        ClearTarget.Disabled = _state?.Target == null;
        if (_state?.Target is { } selected && _cards.TryGetValue(selected, out var selectedCard))
        {
            var brain = selectedCard.Brain;
            TargetName.Text = brain.Name;
            TargetName.ToolTip = brain.Name;
            TargetTier.Text = Loc.GetString(brain.TierName);
            TargetTier.FontColorOverride = brain.TierColor;
            TargetTier.Visible = true;
        }
        else
        {
            TargetName.Text = Loc.GetString("medical-tracking-select-patient");
            TargetName.ToolTip = null;
            TargetTier.Visible = false;
        }
        UpdateSignal();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (VisibleInTree)
            UpdateSignal();
    }

    private void UpdateSignal()
    {
        var distance = Distance.Unknown;
        if (_owner is { } owner && _pointerQuery.TryComp(owner, out var pointer) && pointer.IsActive)
            distance = pointer.DistanceToTarget;

        var key = _state?.Target == null ? "medical-tracking-pinpointer-idle" : distance switch
        {
            Distance.Reached => "medical-tracking-pinpointer-reached",
            Distance.Close => "medical-tracking-pinpointer-close",
            Distance.Medium => "medical-tracking-pinpointer-medium",
            Distance.Far => "medical-tracking-pinpointer-far",
            _ => "medical-tracking-pinpointer-no-signal",
        };
        if (_signalKey == key)
            return;

        _signalKey = key;
        SignalStatus.Text = Loc.GetString(key);
        SignalStatus.ToolTip = SignalStatus.Text;
        SignalStatus.FontColorOverride = _state?.Target == null ? MedicalTrackingUiTheme.Muted : distance switch
        {
            Distance.Reached or Distance.Close => MedicalTrackingUiTheme.Alive,
            Distance.Unknown => MedicalTrackingUiTheme.Warning,
            _ => MedicalTrackingUiTheme.Accent,
        };
    }

    private bool SameEntries(MedicalTrackingPinpointerState state)
    {
        if (_state == null || _state.Brains.Count != state.Brains.Count)
            return false;

        for (var i = 0; i < state.Brains.Count; i++)
        {
            if (_state.Brains[i] != state.Brains[i])
                return false;
        }

        return true;
    }
}
