using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.MedicalTracking;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.MedicalTracking;

[GenerateTypedNameReferences]
public sealed partial class MedicalTrackingPinpointerWindow : FancyWindow
{
    public event Action<NetEntity?>? SelectTarget;
    private MedicalTrackingPinpointerState? _state;

    public MedicalTrackingPinpointerWindow()
    {
        RobustXamlLoader.Load(this);
        ClearTarget.OnPressed += _ => SelectTarget?.Invoke(null);
    }

    public void Setup(EntityUid entity)
    {
        Pointer.SetEntity(entity);
    }

    public void UpdateState(MedicalTrackingPinpointerState state)
    {
        if (SameState(state))
            return;

        Brains.DisposeAllChildren();
        TargetLabel.Text = Loc.GetString("medical-tracking-no-target");
        foreach (var brain in state.Brains)
        {
            var selected = brain.Entity == state.Target;
            var button = new Button { Text = brain.Name, Disabled = selected };
            button.OnPressed += _ => SelectTarget?.Invoke(brain.Entity);
            Brains.AddChild(button);
            if (selected)
                TargetLabel.Text = Loc.GetString("medical-tracking-target", ("name", brain.Name));
        }

        if (state.Brains.Count == 0)
            Brains.AddChild(new Label { Text = Loc.GetString("medical-tracking-no-brains") });

        ClearTarget.Disabled = state.Target == null;
        _state = state;
    }

    private bool SameState(MedicalTrackingPinpointerState state)
    {
        if (_state == null || _state.Target != state.Target || _state.Brains.Count != state.Brains.Count)
            return false;

        for (var i = 0; i < state.Brains.Count; i++)
        {
            if (_state.Brains[i] != state.Brains[i])
                return false;
        }

        return true;
    }
}
