using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.MedicalTracking;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Exodus.MedicalTracking;

[GenerateTypedNameReferences]
public sealed partial class MedicalTrackingWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPlayerManager _player = default!;

    private MedicalTrackingState? _state;
    private NetEntity? _selected;
    private MobState? _filter;
    private readonly List<MedicalTrackingContact> _visible = new();
    private readonly List<NetEntity> _rowOrder = new();
    private readonly Dictionary<NetEntity, MedicalTrackingContactCard> _cards = new();
    private readonly HashSet<NetEntity> _received = new();
    private readonly List<NetEntity> _removed = new();
    private readonly Label _empty = new() { ClipText = true, StyleClasses = { "MedicalMuted" } };
    private TimeSpan _nextAgeUpdate;

    public MedicalTrackingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Stylesheet = MedicalTrackingUiTheme.CreateStylesheet(UserInterfaceManager.Stylesheet);
        AllFilter.OnPressed += _ => SetFilter(null);
        CriticalFilter.OnPressed += _ => SetFilter(MobState.Critical);
        DeadFilter.OnPressed += _ => SetFilter(MobState.Dead);
        Search.OnTextChanged += _ => RefreshList(resetScroll: true);
        MyPosition.OnPressed += _ => Map.FocusMedicalOperator();
        FocusPatient.OnPressed += _ =>
        {
            if (_selected is { } selected && _cards.TryGetValue(selected, out var card))
                Map.FocusMedicalContact(card.Contact.Coordinates);
        };
        Map.MedicalContactSelected += body => SelectContact(body, revealRow: true);
        Contacts.AddChild(_empty);
        UpdateState(new MedicalTrackingState(new List<MedicalTrackingContact>()));
    }

    public void Setup(EntityUid entity)
    {
        Map.Visible = true;
        Map.SetupMedicalMap(entity);
        Map.SetMedicalOperator(_player.LocalEntity);
        Map.FocusMedicalOperator();
        UpdateAges();
    }

    public void UpdateState(MedicalTrackingState state)
    {
        var changed = _state == null || !SameEntries(_state.Contacts, state.Contacts);
        _state = state;
        if (!changed)
            return;

        // Keep row controls and scroll position across samples. Only departed clients are disposed.
        _received.Clear();
        var critical = 0;
        var dead = 0;
        foreach (var contact in state.Contacts)
        {
            _received.Add(contact.Body);
            if (!_cards.TryGetValue(contact.Body, out var card))
            {
                card = new MedicalTrackingContactCard();
                var body = contact.Body;
                card.OnPressed += _ => SelectContact(body);
                _cards.Add(body, card);
                Contacts.AddChild(card);
            }
            card.UpdateContact(contact);
            if (contact.State == MobState.Critical)
                critical++;
            else if (contact.State == MobState.Dead)
                dead++;
        }

        _removed.Clear();
        foreach (var body in _cards.Keys)
        {
            if (!_received.Contains(body))
                _removed.Add(body);
        }
        foreach (var body in _removed)
        {
            _cards[body].Dispose();
            _cards.Remove(body);
        }

        AllFilter.Text = Loc.GetString("medical-tracking-summary-all", ("count", state.Contacts.Count));
        CriticalFilter.Text = Loc.GetString("medical-tracking-summary-critical", ("count", critical));
        DeadFilter.Text = Loc.GetString("medical-tracking-summary-dead", ("count", dead));
        RefreshList();
    }

    private void SetFilter(MobState? filter)
    {
        _filter = filter;
        RefreshList(resetScroll: true);
    }

    private void RefreshList(bool resetScroll = false)
    {
        if (_state == null)
            return;

        AllFilter.Pressed = _filter == null;
        CriticalFilter.Pressed = _filter == MobState.Critical;
        DeadFilter.Pressed = _filter == MobState.Dead;
        _visible.Clear();
        var search = Search.Text.Trim();
        foreach (var contact in _state.Contacts)
        {
            var visible = (_filter == null || _filter == contact.State) &&
                          contact.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase);
            _cards[contact.Body].Visible = visible;
            if (visible)
                _visible.Add(contact);
        }
        _visible.Sort(static (left, right) =>
        {
            var priority = MedicalTrackingDisplay.Priority(left.State).CompareTo(MedicalTrackingDisplay.Priority(right.State));
            if (priority != 0)
                return priority;
            var name = string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase);
            return name != 0 ? name : left.Body.CompareTo(right.Body);
        });
        var orderChanged = _rowOrder.Count != _visible.Count;
        for (var i = 0; !orderChanged && i < _visible.Count; i++)
            orderChanged = _rowOrder[i] != _visible[i].Body;
        if (orderChanged)
        {
            _rowOrder.Clear();
            for (var i = 0; i < _visible.Count; i++)
            {
                var body = _visible[i].Body;
                _rowOrder.Add(body);
                _cards[body].SetPositionInParent(i);
            }
        }
        _empty.Visible = _visible.Count == 0;
        _empty.Text = Loc.GetString(_state.Contacts.Count == 0 ? "medical-tracking-no-bodies" : "medical-tracking-no-matches");
        _empty.ToolTip = _empty.Text;
        if (_selected is { } selected && (!_cards.TryGetValue(selected, out var selectedCard) || !selectedCard.Visible))
            _selected = null;
        UpdateSelection();
        Map.SetMedicalContacts(_visible);
        ClientCount.Text = Loc.GetString("medical-tracking-count-compact", ("shown", _visible.Count), ("total", _state.Contacts.Count));
        if (resetScroll)
            ContactScroll.VScrollTarget = 0;
        UpdateAges();
    }

    private void SelectContact(NetEntity? body, bool revealRow = false)
    {
        if (body == null)
        {
            _selected = null;
            UpdateSelection();
            return;
        }

        if (!_cards.TryGetValue(body.Value, out var card) || !card.Visible)
            return;

        _selected = body;
        UpdateSelection();
        // A map selection also reveals its row without resetting scroll on later signal updates.
        if (revealRow)
            ContactScroll.VScrollTarget = Math.Max(0, card.Position.Y - ContactScroll.Height / 2f + card.Height / 2f);
    }

    private void UpdateSelection()
    {
        foreach (var (body, card) in _cards)
            card.Pressed = body == _selected;
        Map.SelectMedicalContact(_selected);
        FocusPatient.Disabled = _selected == null;
        UpdatePatient();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!VisibleInTree)
            return;

        Map.SetMedicalOperator(_player.LocalEntity);
        if (_timing.CurTime >= _nextAgeUpdate)
            UpdateAges();
    }

    private void UpdateAges()
    {
        var now = _timing.CurTime;
        var interval = TimeSpan.FromSeconds(1);
        if (now >= _nextAgeUpdate)
            _nextAgeUpdate += interval * (1 + (now - _nextAgeUpdate).Ticks / interval.Ticks);
        foreach (var contact in _visible)
            _cards[contact.Body].UpdateAge(now);
        var located = Map.TryGetMedicalOperatorPosition(out var coordinates);
        MyPosition.Disabled = !located;
        OperatorPosition.Text = located
            ? Loc.GetString("medical-tracking-operator-position", ("x", (int) coordinates.X), ("y", (int) coordinates.Y))
            : Loc.GetString("medical-tracking-operator-unavailable");
        UpdatePatient();
    }

    private void UpdatePatient()
    {
        if (_selected is not { } selected || !_cards.TryGetValue(selected, out var card))
        {
            PatientName.Text = Loc.GetString("medical-tracking-select-patient");
            PatientName.ToolTip = null;
            PatientStatus.Text = PatientTier.Text = PatientCoordinates.Text = PatientAge.Text = PatientDistance.Text = string.Empty;
            PatientAge.ToolTip = null;
            PatientStatus.ToolTip = null;
            PatientTier.ToolTip = null;
            PatientDistance.ToolTip = null;
            return;
        }

        var contact = card.Contact;
        PatientName.Text = contact.Name;
        PatientName.ToolTip = contact.Name;
        PatientStatus.Text = MedicalTrackingDisplay.ShortStatus(contact.State);
        PatientStatus.ToolTip = MedicalTrackingDisplay.Status(contact.State);
        PatientStatus.FontColorOverride = MedicalTrackingDisplay.StatusColor(contact.State);
        PatientTier.Text = Loc.GetString(contact.TierName);
        PatientTier.ToolTip = PatientTier.Text;
        PatientTier.FontColorOverride = contact.TierColor;
        PatientCoordinates.Text = Loc.GetString("medical-tracking-coordinates", ("x", (int) contact.Coordinates.X), ("y", (int) contact.Coordinates.Y));
        var seconds = MedicalTrackingDisplay.SignalAge(contact.UpdatedAt, _timing.CurTime);
        PatientAge.Text = Loc.GetString("medical-tracking-age-short", ("seconds", seconds));
        PatientAge.FontColorOverride = MedicalTrackingDisplay.SignalColor(contact.UpdatedAt, _timing.CurTime);
        PatientAge.ToolTip = Loc.GetString(seconds >= MedicalTrackingDisplay.StaleSignalSeconds
            ? "medical-tracking-signal-stale" : "medical-tracking-signal-age", ("seconds", seconds));
        if (!Map.TryGetMedicalOperatorPosition(out var origin))
            PatientDistance.Text = Loc.GetString("medical-tracking-distance-unknown");
        else if (origin.MapId != contact.Coordinates.MapId)
            PatientDistance.Text = Loc.GetString("medical-tracking-other-map");
        else
            PatientDistance.Text = Loc.GetString("medical-tracking-distance", ("distance", (int) MathF.Ceiling(Vector2.Distance(origin.Position, contact.Coordinates.Position))));
        PatientDistance.ToolTip = Loc.GetString("medical-tracking-distance-tip");
    }

    private static bool SameEntries<T>(List<T> left, List<T> right) where T : IEquatable<T>
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (!left[i].Equals(right[i]))
                return false;
        }

        return true;
    }
}
