using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Shipyard.Utilization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Shipyard.Utilization.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipUtilizationConsoleMenu : FancyWindow
{
    public event Action<NetEntity>? OnStart;
    public event Action? OnCancel;

    public ShipUtilizationConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => OnCancel?.Invoke();
    }

    public void UpdateState(ShipUtilizationConsoleInterfaceState state)
    {
        if (state.IsActive)
            ShowActive(state);
        else
            ShowIdle(state);
    }

    private void ShowIdle(ShipUtilizationConsoleInterfaceState state)
    {
        IdleView.Visible = true;
        ActiveView.Visible = false;

        ShipList.RemoveAllChildren();

        StatusLabel.Text = state.Ships.Count == 0
            ? Loc.GetString("ship-utilization-menu-status-empty")
            : Loc.GetString("ship-utilization-menu-status-ready");

        foreach (var ship in state.Ships)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Robust.Shared.Maths.Thickness(0, 2),
                HorizontalExpand = true,
            };
            row.AddChild(new Label
            {
                Text = ship.Name,
                HorizontalExpand = true,
            });

            var payoutKey = ship.VoucherPurchased
                ? "ship-utilization-menu-row-payout-voucher"
                : "ship-utilization-menu-row-payout";
            row.AddChild(new Label
            {
                Text = Loc.GetString(payoutKey, ("payout", ship.Payout.ToString("N0"))),
                Margin = new Robust.Shared.Maths.Thickness(8, 0, 8, 0),
            });

            var startBtn = new Button
            {
                Text = Loc.GetString("ship-utilization-menu-start-button"),
                Disabled = ship.LockedByOtherConsole,
                ToolTip = ship.LockedByOtherConsole
                    ? Loc.GetString("ship-utilization-menu-locked-tooltip")
                    : null,
            };
            var shipCapture = ship.Ship;
            startBtn.OnPressed += _ => OnStart?.Invoke(shipCapture);
            row.AddChild(startBtn);

            ShipList.AddChild(row);
        }
    }

    private void ShowActive(ShipUtilizationConsoleInterfaceState state)
    {
        IdleView.Visible = false;
        ActiveView.Visible = true;

        ActiveShipNameLabel.Text = Loc.GetString("ship-utilization-menu-active-ship",
            ("name", state.ActiveShipName ?? string.Empty));
        ActivePayoutLabel.Text = Loc.GetString("ship-utilization-menu-active-payout",
            ("payout", state.ActivePayout.ToString("N0")));
        ActiveTimeLabel.Text = Loc.GetString("ship-utilization-menu-active-time",
            ("seconds", state.ActiveSecondsRemaining));

        ProgressBar.MaxValue = state.ActiveTotalSeconds > 0 ? state.ActiveTotalSeconds : 1;
        ProgressBar.Value = state.ActiveTotalSeconds > 0
            ? state.ActiveTotalSeconds - state.ActiveSecondsRemaining
            : 0;
    }
}
