using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Shipyard.Utilization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Shipyard.Utilization.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipUtilizationConsoleMenu : FancyWindow
{
    public event Action<NetEntity>? OnStart;
    public event Action? OnCancel;

    public ShipUtilizationConsoleMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ShipUtilizationConsoleInterfaceState state)
    {
        ShipList.RemoveAllChildren();

        if (state.IsActive)
        {
            StatusLabel.Text = Loc.GetString("ship-utilization-menu-status-active",
                ("seconds", state.ActiveSecondsRemaining),
                ("payout", state.ActivePayout.ToString("N0")));

            var cancelRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Robust.Shared.Maths.Thickness(0, 2),
                HorizontalExpand = true,
            };
            cancelRow.AddChild(new Label
            {
                Text = Loc.GetString("ship-utilization-menu-active-row"),
                HorizontalExpand = true,
            });
            var cancelBtn = new Button
            {
                Text = Loc.GetString("ship-utilization-menu-cancel-button"),
                StyleClasses = { "OpenRight" },
            };
            cancelBtn.OnPressed += _ => OnCancel?.Invoke();
            cancelRow.AddChild(cancelBtn);
            ShipList.AddChild(cancelRow);
            return;
        }

        StatusLabel.Text = state.Ships.Count == 0
            ? Loc.GetString("ship-utilization-menu-status-empty")
            : Loc.GetString("ship-utilization-menu-status-ready");

        foreach (var ship in state.Ships)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Robust.Shared.Maths.Thickness(0, 2),
                HorizontalExpand = true,
            };
            row.AddChild(new Label
            {
                Text = ship.Name,
                HorizontalExpand = true,
            });

            var payoutKey = ship.VoucherPurchased
                ? "ship-utilization-menu-row-payout-voucher"
                : "ship-utilization-menu-row-payout";
            row.AddChild(new Label
            {
                Text = Loc.GetString(payoutKey, ("payout", ship.Payout.ToString("N0"))),
                Margin = new Robust.Shared.Maths.Thickness(8, 0, 8, 0),
            });

            var startBtn = new Button
            {
                Text = Loc.GetString("ship-utilization-menu-start-button"),
                Disabled = ship.LockedByOtherConsole,
                ToolTip = ship.LockedByOtherConsole
                    ? Loc.GetString("ship-utilization-menu-locked-tooltip")
                    : null,
            };
            var shipCapture = ship.Ship;
            startBtn.OnPressed += _ => OnStart?.Invoke(shipCapture);
            row.AddChild(startBtn);

            ShipList.AddChild(row);
        }
    }
}
