using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class BankATMMenu : FancyWindow
{
    public Action? WithdrawRequest;
    public Action? DepositRequest;
    public int Amount;

    public BankATMMenu()
    {
        RobustXamlLoader.Load(this);

        WithdrawButton.OnPressed += OnWithdrawPressed;
        DepositButton.OnPressed += OnDepositPressed;
        Title = Loc.GetString("bank-atm-menu-title");
        WithdrawEdit.OnTextChanged += OnAmountChanged;
    }

    public void SetBalance(int amount, long savings)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(amount);
        SavingsLabel.Text = BankSystemExtensions.ToSpesoString(savings);
    }

    // Exodus-begin corporate ATM commission display
    public void SetDeposit(
        int amount,
        int sectorDeposit,
        int savingsDeposit,
        int atmFee,
        int companyCommission)
    {
        DepositButton.Disabled = amount <= 0;
        if (amount >= 0) // Valid
        {
            DepositLabel.Text = BankSystemExtensions.ToSpesoString(sectorDeposit);
            DepositLabelUT.Text = BankSystemExtensions.ToSpesoString(savingsDeposit);
            AtmFeeLabel.Text = BankSystemExtensions.ToSpesoString(atmFee);
            CompanyCommissionLabel.Text = BankSystemExtensions.ToSpesoString(companyCommission);
        }
        else
        {
            DepositLabel.Text = Loc.GetString("bank-atm-menu-cash-error");
            DepositLabelUT.Text = Loc.GetString("bank-atm-menu-cash-error");
            AtmFeeLabel.Text = Loc.GetString("bank-atm-menu-cash-error");
            CompanyCommissionLabel.Text = Loc.GetString("bank-atm-menu-cash-error");
        }
    }
    // Exodus-end

    public void SetEnabled(bool enabled)
    {
        WithdrawButton.Disabled = !enabled;
    }

    private void OnWithdrawPressed(BaseButton.ButtonEventArgs obj)
    {
        WithdrawRequest?.Invoke();
    }

    private void OnDepositPressed(BaseButton.ButtonEventArgs obj)
    {
        DepositRequest?.Invoke();
    }

    private void OnAmountChanged(LineEdit.LineEditEventArgs args)
    {
        if (int.TryParse(args.Text, out var amount))
        {
            Amount = amount;
        }
    }
}
